### ISSUE TITLE
Cannot enter in hero "demo" mode

### ISSUE THREAD

**Issue by micaelbergeron** [ValveSoftware/Dota-2#10]
The game will crash during the loading (with the dota2 logo on black background).
If you need any more logs, just tell me.

**Comment by kon14** [comment]
The very same issue affects me as well. Game crashes after a map load attempt. The equipped loading screen shows up, then the game crashes, possibly after showing the new dota2 logo on black background screen:

> ERROR: ld.so: object '/home/kon14/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored. assert_20150623103816_1.dmp[6177]: Uploading dump (out-of-process) /tmp/dumps/assert_20150623103816_1.dmp /home/kon14/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 98: 6101 Illegal instruction (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@" Game removed: AppID 570 "Dota 2", ProcID 6101 assert_20150623103816_1.dmp[6177]: Finished uploading minidump (out-of-process): success = no assert_20150623103816_1.dmp[6177]: error: HTTP response code said error assert_20150623103816_1.dmp[6177]: file ''/tmp/dumps/assert_20150623103816_1.dmp'', upload no: ''HTTP response code said error'' pid 6177 != 6175, skipping destruction (fork without exec?)

I'll upload the crash dump in a while, are there any other logs or valuable pieces of output we could gather?

**Comment by micaelbergeron** [comment]
Here is my config http://ix.io/jgi

**Comment by gekkey** [comment]
I am also getting a crash as the game is loading. This is on Arch kernel 4.0.5 x64 and an intel HD 3000.

```
Game update: AppID 570 "Dota 2", ProcID 8782, IP 0.0.0.0:0
ERROR: ld.so: object '/home/gekkey/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gekkey/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 8784 != 8783, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/gekkey/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gekkey/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198023505915 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198023505915
Setting breakpad minidump AppID = 373300
Fontconfig warning: "/home/gekkey/hold/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/gekkey/hold/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
ERROR: ld.so: object '/home/gekkey/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20150623154845_1.dmp[8794]: Uploading dump (out-of-process)
/tmp/dumps/crash_20150623154845_1.dmp
/home/gekkey/hold/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 98:  8786 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 8786 
crash_20150623154813_1.dmp[8623]: Finished uploading minidump (out-of-process): success = no
crash_20150623154813_1.dmp[8623]: error: HTTP response code said error
crash_20150623154813_1.dmp[8623]: file ''/tmp/dumps/crash_20150623154813_1.dmp'', upload no: ''HTTP response code said error''
pid 8623 != 8622, skipping destruction (fork without exec?)
crash_20150623154845_1.dmp[8794]: Finished uploading minidump (out-of-process): success = no
crash_20150623154845_1.dmp[8794]: error: HTTP response code said error
crash_20150623154845_1.dmp[8794]: file ''/tmp/dumps/crash_20150623154845_1.dmp'', upload no: ''HTTP response code said error''
pid 8794 != 8793, skipping destruction (fork without exec?)
```

**Comment by HarlemSquirrel** [comment]
I am also experiencing this crash. I have not been able to get the game to launch at all, it just crashes after the launch animation on GNOME or Cinnamon with all updates installed. 
Arch Linux 64-bit
kernel 4.0.5
mesa 10.6
Sapphire R9 270X on open source drivers

**Comment by gdrewb-valve** [comment]
Did the failure report upload work for anybody?  If not do any of you have crash dumps that you can post?

**Comment by kon14** [comment]
I nearly commented before the upload, stdout used to be like:

> assert_20150624221558_1.dmp[5649]: Finished uploading minidump (out-of-process): success = no
assert_20150624221558_1.dmp[5649]: error: HTTP response code said error
assert_20150624221558_1.dmp[5649]: file ''/tmp/dumps/assert_20150624221558_1.dmp'', upload no: ''HTTP response code said error''

then it seems it managed to upload it after a retry:

> assert_20150624221730_1.dmp[5703]: Finished uploading minidump (out-of-process): success = yes
assert_20150624221730_1.dmp[5703]: response: CrashID=bp-868fee45-17b5-44f4-8c4a-e3d7b2150624
assert_20150624221730_1.dmp[5703]: file ''/tmp/dumps/assert_20150624221730_1.dmp'', upload yes: ''CrashID=bp-868fee45-17b5-44f4-8c4a-e3d7b2150624''

[Here](https://www.dropbox.com/s/cwkt0ro89rvwxtb/assert_20150624221558_1.dmp?dl=0)'s my log though, already posted a previous one in #14, I think this thread is a bit confusing.

Half people here seem to replying for a crash on startup while the title mentions a crash on map loading, just to clear things up: I'm with the title.

**Comment by pwuertz** [comment]
Same problem, crash after loading screen (demo mode/bot game/normal game).
Also got the HTTP error on upload, but here is my crash dump:
https://www.dropbox.com/s/g6ypot84hfd1i1e/crash_20150624212504_1.dmp?dl=0

**Comment by pwuertz** [comment]
Also got an AMD CPU by the way, apparently as everybody else that reports these crashes when trying to load a game.

**Comment by pwuertz** [comment]
gdb backtrace in case this is useful (same as in #14)
```
Program received signal SIGILL, Illegal instruction.
0x00007f7d6ca6df77 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
(gdb) bt
#0  0x00007f7d6ca6df77 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#1  0x00007f7d6ca6e146 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#2  0x00007f7d6ca6e3bf in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#3  0x00007f7d6ba79b9a in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#4  0x00007f7d6c3bdc86 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#5  0x00007f7d6b63f76c in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so
#6  0x00007f7d828d582f in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#7  0x00007f7d828819f1 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#8  0x00007f7d8287b246 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#9  0x00007f7d82748165 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#10 0x00007f7d82748781 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#11 0x00007f7d8273f2d2 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#12 0x00007f7d82741c38 in ?? () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#13 0x00007f7d82741dda in Source2Main () from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so
#14 0x00007f7d899680c1 in ?? ()
#15 0x00007f7d88a0aa40 in __libc_start_main (main=0x7f7d89967f50, argc=1, argv=0x7ffda96b5468, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffda96b5458) at libc-start.c:289
#16 0x00007f7d899681bd in _start ()
```

**Comment by micaelbergeron** [comment]
Here is a dump: https://copy.com/UEAbPtuUsk9edkoc

**Comment by pwuertz** [comment]
@gdrewb-valve Apparently Dota2 Reborn Beta (Linux) was built with "wrong" compiler flags. The illegal instruction that is causing the application to terminate is "PSHUFB", which is part of the SSSE3 instruction set, only supported by Intel. It is not valid on AMD Phenom, which people reporting the bug seem to use.

**Comment by gdrewb-valve** [comment]
Correct, and an upcoming update will fix that.

**Comment by HarlemSquirrel** [comment]
I just downloaded an update. The game "appears" to launch but nothing happens. I seem to get a freeze of my desktop until I do an Alt+Tab and then close DOTA 2. There is no dmp file.

**Comment by gdrewb-valve** [comment]
@HarlemSquirrel , you should open a separate issue to cover what you're seeing.

**Comment by gdrewb-valve** [comment]
Does the 6/26 update fix this?

**Comment by pwuertz** [comment]
No, dota reborn still crashes because of another PSHUFB instruction in `game/bin/linuxsteamrt64/libscaleformui_4_gl.so`.

```
(gdb) bt
#0  0x00007efd248d87ed in vpx_reset_mmx_state ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#1  0x00007efd248ae4ef in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#2  0x00007efd248ad2c8 in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#3  0x00007efd248ac8c6 in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#4  0x00007efd248a787c in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#5  0x00007efd248a62a6 in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#6  0x00007efd244bfda4 in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#7  0x00007efd244bfde2 in ?? ()
   from /home/pwuertz/.local/share/Steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64/libscaleformui_4_gl.so
#8  0x00007efd3961b6aa in start_thread (arg=0x7efd050c3700)
    at pthread_create.c:333
#9  0x00007efd39938eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by kon14** [comment]
The new update seems to have fixed it for me, demo map loads and plays without issues.

[Here](http://pastebin.com/DuxZzFp1)'s the system info once again.

**Comment by pwuertz** [comment]
Oh, you are right. The demo map works... so technically, this exact issue is resolved now :D. But it would be really nice to have the rest of dota reborn compiled in a non-SSSE3 compatible way as well though ;)

**Comment by kon14** [comment]
I guess the actual issue reported in this thread is not the demo map itself, but rather map loading in general so unless considering the title literally the issue remains unresolved for now.

The actual DotA map is probably going to be unplayable as well, did you try it out?

**Comment by pwuertz** [comment]
@kon14, yea.. it was a joke. No that's why I didn't notice that the 26.6. update made loading the demo mode possible, I was trying to load a bot match which still failed. The reason for all of these crash-on-loading-issues is well known now, but for some reason Valve didn't recompile all of the dota libraries, so some are still broken for us.

**Comment by kon14** [comment]
I guess a reason for that would be the extraction of smaller patches so as to not infuriate the linux users not experiencing that particular issue?

**Comment by pwuertz** [comment]
Doesn't make much sense, must have been a mistake. Could be that `libscaleformui_4_gl.so` is built with compiler flags that are defined separately from the ones that were fixed for recompiling `libserver.so`. Or they did an incremental build where a change in compiler flags doesn't cause a rebuild of binaries if their source wasn't modified. Guess we have to wait..

**Comment by khill** [comment]
Same for me - the "demo hero" function works and allows me to play in demo mode.  I still crash when I try to launch a bot game.  Latest system info link is here:

https://gist.github.com/khill/d8ab80b5b3b154a2f1e2

**Comment by gdrewb-valve** [comment]
Thanks, we'll fix the libscaleform issue.

**Comment by urbinek** [comment]
same problem here, game crashes after loading map - #155

**Comment by kleinsasserm** [comment]
same problem here, demo works but no other mode. Neither bot game nor overthrow. It crashs after loading map. AMD cpu and AMD graphics card.

**Comment by gdrewb-valve** [comment]
Can people hitting the libscaleform segfault try the 6/30 update?

**Comment by pwuertz** [comment]
Works now, thanks a lot!

**Comment by gdrewb-valve** [comment]
@micaelbergeron, based on other posts of yours I believe your crash might be something different than the SSSE3 / illegal instruction problem.  Let me know if you're still having crashes.

**Comment by KuriKai** [comment]
Works for me now. Thanks guys

**Comment by kon14** [comment]
Works like a charm, thank you

**Comment by kleinsasserm** [comment]
Killswitch gone - works like a charm, thank you!

**Comment by urbinek** [comment]
Same here, update solved problem

11/10 would submit again ;)

**Comment by realbyx** [comment]
I didnt understand what to do to fix the problem. Can any of you explain to me please?

**Comment by urbinek** [comment]
in my case - passive wait for update ;)

**Comment by micaelbergeron** [comment]
I think this issue is now resolved, as the game doesn't crash anymore on SSSE3 illegal instructions. We should use other issues to track related bugs.
