### ISSUE TITLE
Mac: Fullscreen mode with second monitor

### ISSUE THREAD

**Issue by codycurley** [ValveSoftware/Dota-2#11]
When using fullscreen mode and dual monitors, my mouse will track over to the second screen.

On the main client, the second monitor continued to work as intended. It would show my desktop or browser while in Reborn it goes black.

Specs: https://cloudup.com/c2e8DUzlhtG

**Comment by codycurley** [comment]
Testing further, the mouse only tracks to the second monitor randomly after switching the fullscreen mode. If you quit and restart it locks it to the monitor Reborn is running in.

Second monitor going black is still an issue.

**Comment by codycurley** [comment]
Seems fixed in last patch!

**Comment by gdrewb-valve** [comment]
Unfortunately any change here from the 6/24 update wasn't intentional so this may not stay fixed.

**Comment by gdrewb-valve** [comment]
Can you pick up the 7/20 update and report back on whether this is still an issue?

**Comment by codycurley** [comment]
@davidw-valve I see the added full screen option. This is getting closer. The mouse locks to the app, but Reborn still isn't opening up in it's own ["space"](https://en.wikipedia.org/wiki/Spaces_%28software%29) like the current app does.

The causes issues while wanting to switch spaces as it causes Reborn to minimize instead of stay in another space.

**Comment by gdrewb-valve** [comment]
We had to turn off using separate spaces because they were causing some graphics issues, so at the moment that's expected behavior.

**Comment by codycurley** [comment]
Then my issue is resolved.

Now, I'll be adding an edge pan stuttering / FPS drop issue that's consistent for me across all graphic settings and resolutions. Has the dev team already seen issues like this? Specifically when you pan around the mid tower.

**Comment by gdrewb-valve** [comment]
I haven't seen it, go ahead and open an issue.

**Comment by gdrewb-valve** [comment]
Closing as the original issue is resolved.

**Comment by EdbertChan** [comment]
Problem still exists on Macbook version of Dota 2 Reborn. I'm fairly certain its only an issue in the newest version of OSX since this wasnt a problem with me before the OSX update.

Specs:
OSX Version 10.10.5
MacBook Pro 13-inch Mid 2012
Processor 2.9 GHz Intel Core i7
Memory 8GB 1600 MHZ DDR3
Graphics Intel HD Graphics 4000 1024 MB

**Comment by fwsGonzo** [comment]
Having issues on dual-monitors, same sized monitors of same type, Ubuntu X11
The physical window area is on my right screen, while the framebuffer is rendered on my left
As in: I can close the game from clicking on the top-right of my right monitor, while its being rendered on the left. In addition, cannot click anywhere on rendered area without simply switching task to whatever is underneath

I managed to make it windowed, and that makes it possible to use the client, at least

Second problem:
I change the settings back to borderless fs, everything is fine as expected - as I moved it to the rightmost monitor. I then restart the game and lo and behold - please save/load the window creation settings.. Now I have to do the whole thing again :watch:

**Comment by filipminev** [comment]
+1 having the same issue on OSX

**Comment by netsap** [comment]
Hello, I'm still facing this problem on Manjaro

**Comment by ahmedu007** [comment]
This is still an issue on MacBook Pro 2018, High Sierra

**Comment by murilomendes** [comment]
Same problem here.

**Comment by giancarlosisasi** [comment]
same here!

**Comment by Delitants** [comment]
Nobody cares, apparently.

**Comment by kjmj** [comment]
Having this issue as well. Very disappointing, as this is an issue with Dota and not Mac. Other apps in full screen lock the mouse to that screen flawlessly, Dota is the only program I have this issue with.

**Comment by brandonshough** [comment]
Same issue, is this going to be addressed? Very frustrating!

**Comment by mandal-ts** [comment]
There are 2 solution:

close the laptop lid
use mirror mode on display setting

**Comment by Delitants** [comment]
> There are 2 solution:
> 
> close the laptop lid
> use mirror mode on display setting

You f kidding me, right?? Why you assuming it's a laptop at all? Instead of silly answers, fix it as it suppose to be. Shame.

**Comment by cerireyhan** [comment]
It's 2020 and seriously there is not solution except mirroring screens, amazing..

**Comment by Delitants** [comment]
Yes, and they just closed the issue ticket. What a jerks. This is why I've stopped playing this game, because I'm tired unplugging second monitor and plug it back when done, messing up my icons on the desktop.

**Comment by nldoty** [comment]
The ticket was closed in 2015 because _the issue was resolved in 2015_. If you'd like to bring attention to this issue again, I'd recommend looking through the open tickets and seeing if it exists - if not, add it once again.

**Comment by valentin994** [comment]
2021 and still not fixed ehh

**Comment by Delitants** [comment]
> 2021 and still not fixed ehh

Because they don't care

**Comment by rafagonc** [comment]
2021 and I still need to close laptop lid to be able to play decently, and with closed lid, no microphone. Awesome experience

**Comment by ps99** [comment]
Second Monitor Settings: `Use as: Main display`
It works for me.

**Comment by NailKhalimov** [comment]
> Second Monitor Settings: `Use as: Main display`
> 
> It works for me.

How can set it as second monitor?

**Comment by qbalsdon** [comment]
Howdy folks,

I was just [browsing around the wiki][0] and found that you can put

`-sdl_displayindex #` 

in the launch options under Settings (In Steam before launch) -> Properties -> General -> Launch Options. `#` is a numbered index starting with primary screen as 0. So try 1, 2, etc.

I used 

`-sdl_displayindex 1`

and it worked for me on Mac OSX

[0]: https://dota2.fandom.com/wiki/Launch_Options
