### ISSUE TITLE
Bug in DotA2 Interface - Ubuntu 14.04 (Linux) - Nvidia GeForce GT430

### ISSUE THREAD

**Issue by Escouflenfer** [ValveSoftware/Dota-2#114]
The game start perfectly good, the menu is beautiful : 
![dota_1](https://cloud.githubusercontent.com/assets/13065859/8379390/f099196c-1c1f-11e5-9a8c-abc74a96cf9c.png)
But when I get into a game, buttons doesn't display at all, There are big problems in game with the rendering but the game itself work normally
![dota_2](https://cloud.githubusercontent.com/assets/13065859/8379392/f09eae04-1c1f-11e5-9c82-a3c02c623c9a.png)
![dota_3](https://cloud.githubusercontent.com/assets/13065859/8379391/f09ceab0-1c1f-11e5-9769-aa5874e26d6a.png)

**Comment by gdrewb-valve** [comment]
Likely to be the same core issue that will get fixed in the next update.

**Comment by xdevelnet-inc** [comment]
Same issue...

New update comes today - bug still exist :(

**Comment by gdrewb-valve** [comment]
There hasn't been a Reborn update today.  We'll close this issue when the update is out.

**Comment by Giansama** [comment]
I use Arch Linux, and have this bug too.
I notice the problem is when I change the game resolution to less than 1080p and use the game in fullscreen.

![captura de tela de 2015-06-22 23-27-45](https://cloud.githubusercontent.com/assets/10815693/8382124/e8255c78-1c06-11e5-8726-3e641309989f.png)

**Comment by Tele42** [comment]
There are other reports that nvidia-drivers 331.xx have problems with the game, while new 340.xx and 352.xx are fixed.

**Comment by gdrewb-valve** [comment]
After updating your driver and picking up the 6/26 Reborn update is ths still happening?

**Comment by mentegy** [comment]
got the same issue (nvidia 331.xx / ubuntu 14.04). After upgrading to 15.04 and 346.xx it's gone!
Notice that 346.xx requires ubuntu 15.04.

**Comment by CommanderAlchemy** [comment]
Same issue for me parts of the UI does not render correctly.
nvidia 352.21
![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8395038/b16fb718-1d56-11e5-8477-b04d124af3ef.png)

I found that for me its related to how Dota detects my resolution. For some reason it launches on screen 0 instead of primary that is 1. I have kwinrule that moves Dota 2 to correct position however it seems that Dota 2 does not react correctly to this and shows the above, I somehow forced it to Window mode and the Interface was shown correctly.

**Comment by danginsburg** [comment]
Duplicate of #48 .  Workarounds have been checked in for NVIDIA 331.

**Comment by CommanderAlchemy** [comment]
@danginsburg should i create a new bug for my issue?

**Comment by gdrewb-valve** [comment]
Yes, go ahead and open one specifically for the multimon window moving.
