### ISSUE TITLE
Green screen after battle pass update (May 8, 2018)

### ISSUE THREAD

**Issue by s-ruangdech** [ValveSoftware/Dota-2#1451]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookAir7,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    CPU Family:  0x6
    CPU Model:  0x3d
    CPU Stepping:  0x4
    CPU Type:  0x0
    Speed:  1600 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.11.6 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 6000
    Driver Version:  1.2
    Driver Date: 0 0 0
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x8086
    DeviceID:  0x1626
    Revision:  0x9
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 11.42" x 7.09" (13.43" diag)
                                            29.0cm x 18.0cm (34.1cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  358880 Mb
    Largest Free Hard Disk Block:  113679 Mb
    VR Headset: None detected

* Have you checked for system updates?: [Yes/No]
Yes
* Are you using the latest stable video driver available for your system? [Yes/No]
Yes
* Have you verified the game files?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

After the TI pass update today (May 8, 2018), When the game start, the screen turned green. The outline of the characters can still be seen, but blurry. The other part of the map is not green, but a plain with some undefined texture. I tried restarting the game, the steam, and my computer but nothing helps.

Note: My steam library is on my external hard drive.

Thanks

#### Steps for reproducing this issue:

1. Start any game.

**Comment by gdrewb-valve** [comment]
Likely the rendering issue that is affecting all platforms, the larger team is taking a look.

**Comment by dawik** [comment]
Experiencing same issues on nvidia and arch linux

**Comment by sebastiansilbernagl** [comment]
![error_console](https://user-images.githubusercontent.com/19287430/39786477-0c616902-5321-11e8-94f9-48459ec529e1.jpg)

Just adding to what @s-ruangdech said, when I scroll around on the map, I get a green screen. Attached, the console with errors.

**Comment by d4ve89** [comment]
I am running arch linux on kernel  4.16.5-1, nvidia / opengl. I get similar glitches and almost the same error messages in my console:

`texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2220):ResourceHandleToData(  ) failed! Falling back to error texture!
texturebase.cpp(2198):ResourceHandleToData(  ) failed! Falling back to error texture!
[SceneSystem] Error: View "Player 0", layer "World Forward": 
	Unable to allocate space for scratch render target "game.rtoutputcolor1010102..." 
	(type = original, MSAA = off, Size = 1918x1053, Fmt = RGBA1010102)!
	(If you are in tools mode, you can add SVF_TOOL_VIEW to your view to allow dynamic allocations.)`

![green2](https://user-images.githubusercontent.com/37449430/39787489-dfc3e442-5325-11e8-91e2-018a14e51f04.jpg)

**Comment by mkhamat** [comment]
Same here, running on Ubuntu 18.04 LTS. (Mesa, AMD)

**Comment by danginsburg** [comment]
Does it work if you turn on High Quality water?  If so, we have a fix incoming.

**Comment by gabrielboliveira** [comment]
@danginsburg Same on macOS. Fixed when I changed shadows to medium (instead of disabled).

**Comment by d4ve89** [comment]
looks like it has been fixed a minute ago! thanks for the speedy work :)

**Comment by mkhamat** [comment]
Now everything is fine, thank you

**Comment by gdrewb-valve** [comment]
Is anybody still seeing problems after the most recent update and validating your Dota install?

**Comment by s-ruangdech** [comment]
It's fixed. Thanks for the quick response.
