### ISSUE TITLE
Crashes on "On my way" ping, with FT_Load_Glyph errors in console

### ISSUE THREAD

**Issue by anko** [ValveSoftware/Dota-2#1504]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/anko/f3587996bb83526314e166c5983f1933
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes; Nvidia proprietary 390.87.
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Using the "On my way" ping *sometimes* crashes the game. The final lines of the `-con_logfile` log are these:

```
Error in GetCharRGBA FT_Load_Glyph of 0x6b / 0x4c in Radiance (symbol 0): 0x6
[VScriptDbg] LuaDbg - Debugging stopped
```

The specific hex codes on the second-last line differ. Here are a few variations I got:

 - ```
   Error in GetCharRGBA FT_Load_Glyph of 0x75 / 0x56 in Radiance (symbol 0): 0x1
   ```
 - ```
   Error in GetCharRGBA FT_Load_Glyph of 0x75 / 0x56 in Radiance (symbol 0): 0x3
   ```
 - ```
   Error in GetCharRGBA FT_Load_Glyph of 0x67 / 0x48 in Radiance (symbol 0): 0x1
   ```
 - ```
   Error in GetCharRGBA FT_Load_Glyph of 0x6c / 0x4d in Radiance (symbol 0): 0x6
   ```

Sometimes there are multiple *Error in GetCharRGBA FT_Load_Glyph* errors in the last few lines of log.

I have observed this happening in matchmade games, bot games, local lobby, and demo mode.

[Here's a log for a crash immediately on loading into demo mode and "On my way"-pinging.](https://gist.github.com/anko/eab67fcb5ee89ad0bf80599a396ec24a)

[Here's a log where it only crashed on the fourth hero that I switched to and "On my way"-pinged as.](https://gist.github.com/anko/2fa1e8e4665554ccee3f51d012c9734e) 

#### Steps for reproducing this issue:

1. Enter demo mode as any hero.
2. "On my way"-ping the ground in front of you.
3. Press "Select New Hero". Select a different hero and "Return to Demo".
4. "On my way"-ping the ground in front of you.

Repeat steps 3 and 4 until the game crashes.

Alternatively, exit demo mode fully in between heroes. Same result.

Based on a bunch of testing, the chance of crashing seems to increase with how many heroes have "On my way"-pinged since I last fully restarted the game. Who it is (me or another player) doesn't seem to matter.

#### Workaround attempts

I tried preloading my system `libfreetype` with `LD_PRELOAD='/usr/lib/libfreetype.so.6.16.1' steam`. This crashes the same way.

#### Similar issues

 - Seems similar to #1443.
 - Text corruption similar to https://github.com/ValveSoftware/Dota-2/issues/1306.

**Comment by sylware** [comment]
same here, the text is most of the time garbled, freetype 2.9.1

**Comment by sylware** [comment]
After further investigation and testing: dota2 uses the "panorama" text shaper (proprietary) but it seems to be statically linked with fontconfig and freetype (no mapping of my system freetype/fontconfig or steam runtime freetype/fontconfig in dota2 process).
I saw that my system dejavu font was mapped in dota2 process, but hiding it did not fix anything. Ofc, each time I did clear the dota2 panorama fontconfig cache (WINDOWS...)
Before I run out of option, I noticed the statically linked fontconfig in panorama is parsing my sys /etc fontconf config. I'll test dota2 with this config hidden.

**Comment by sylware** [comment]
Unfortunately, even with my system fontconfig conf hidden, dota is crashing. Nasty annoying bug.

**Comment by sylware** [comment]
A small update, I notice when the text is garbled (but not crashing), often, the letter 'p' is missing from the hero name.

**Comment by sylware** [comment]
Is this fixed? I have not played many heroes, but the bug seems gone.
Anyone to confirm?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by sylware** [comment]
It has been fixed on my system for a long time. I was waiting for the other
users to confirm.

**Comment by anko** [comment]
Pardon my inattentiveness. I think this is indeed fixed. Thank you! :heart:

**Comment by XuShulei** [comment]
This error still exist while I login client with language setting to Simplified Chinese. The error could not be reproduced when I set language to English, not sure about other languages

**Comment by kisak-valve** [comment]
Hello @XuShulei, the investigation on this issue report concluded years ago and the issue you've encountered is unlikely to be from the same root cause. Please open a new issue report.
