### ISSUE TITLE
[Linux] Item names do not show

### ISSUE THREAD

**Issue by computerquip** [ValveSoftware/Dota-2#16]
I don't recall this issue on Windows. Have a pic:

![Some Stuff](http://images.akamai.steamusercontent.com/ugc/525015750982213228/CBE9EA4C5F0AF768563978D2F4576AC5C25ECE07/)

This happens with all items.

**Comment by Kirov123** [comment]
All sets are the same. Any inscribed item is simply called "Inscribed."

**Comment by gdrewb-valve** [comment]
You look to be missing the localized names.  Can you verify your local file cache?

**Comment by MaelRL** [comment]
I have the same issue and verifying the local file cache didn't fix it.

Item and gem's descriptions have the same problem as well.

**Comment by Kirov123** [comment]
I tried validating cache, it said everything validated, and names are still
wrong.

**Comment by Turmfalke2** [comment]
the console also has the same issue,
#Console_Title
#SysMenu_Minimize
#SysMenu_Maximize
#SysMenu_Close
and the submit button is also labeled #Cons...

**Comment by Kirov123** [comment]
For me, the close button is just a "r"

**Comment by gdrewb-valve** [comment]
Can you post your console output from starting the game?

**Comment by MaelRL** [comment]
Here is mine : 

```
ILocalize::AddFile() failed to load file "Resource/valve_english.txt".
ILocalize::AddFile() failed to load file "Resource/vgui_english.txt".
CEntitySystem::BuildEntityNetworking (parallel build of server) took 154.665 msecs for 652 out of 667 classes
Item set ambry_set: Bundle definition "Major Allstars Tournament Bundle" was not found but was inferred from the data.
Item set antipodeans: Bundle definition "Antipodean Allies" was not found but was inferred from the data.
Item set arc_of_manta: Bundle definition "Arcs of Manta Pack" was not found but was inferred from the data.
Item set baleful_hollow: Bundle definition "Baleful Hollow" was not found but was inferred from the data.
Item set basher_of_game_skulls: Bundle definition "The Basher Blades" was not found but was inferred from the data.
Item set bedrock_serenity: Bundle definition "GG League Season 2" was not found but was inferred from the data.
Item set broodmother_nephropod_plate: Bundle definition "Steelweb of Pytheos Set" was not found but was inferred from the data.
Item set chaos_knight_mephistopheles: Bundle definition "Arms of Burning Turmoil Set" was not found but was inferred from the data.
Item set cloak_of_the_fallen: Bundle definition "Red Bull Battle Grounds Bundle" was not found but was inferred from the data.
Item set deathprophet_mortalcoil: Bundle definition "Regalia of the Mortal Coil Set" was not found but was inferred from the data.
Item set dusklight_marauder: Bundle definition "SLTV Star Series Season 11" was not found but was inferred from the data.
Item set elemental_ice: Bundle definition "Elemental Ice Infusion" was not found but was inferred from the data.
Item set empress_of_the_sea: Bundle definition "Dota Regions: Season 2" was not found but was inferred from the data.
Item set eye_of_the_beholder: Bundle definition "i League Season 3" was not found but was inferred from the data.
Item set fatal_blossom: Bundle definition "Fatal Blossom" was not found but was inferred from the data.
Item set fluttering_amethyst: Bundle definition "i-League Season 2" was not found but was inferred from the data.
Item set golden_basher_of_mage_skulls: Bundle definition "Golden Basher Blades" was not found but was inferred from the data.
Item set heavenly_light: Bundle definition "TEvent Dota 2 Season 1" was not found but was inferred from the data.
Item set incandescent_liturgy: Bundle definition "Incandescent Liturgy" was not found but was inferred from the data.
Item set juggernaut_kogu_warrior: Bundle definition "Arms of the Gwimyeon Warrior Set" was not found but was inferred from the data.
Item set lina_fiery_soul_arcana: No bundle definition specified or found.Item set majesty_of_the_forbidden_sands: Bundle definition "Red Bull Battle Grounds Bundle" was not found but was inferred from the data.
Item set moonshard_overgrowth: Bundle definition "Esportal Dota 2 League" was not found but was inferred from the data.
Item set oath_of_the_afflicted_soul: Bundle definition "Oath of the Afflicted Soul" was not found but was inferred from the data.
Item set razor_shard_of_revenant: Bundle definition "joinDOTA MLG Pro League Season 1" was not found but was inferred from the data.
Item set rising_chaos: Bundle definition "Rising Chaos" was not found but was inferred from the data.
Item set scavenger_basilisk: Bundle definition "Korean Dota League Season 4" was not found but was inferred from the data.
Item set shambling_trickster: Bundle definition "Razer Think Fast Season 2" was not found but was inferred from the data.
Item set slardar_sea_djinn: Bundle definition "SLTV Star Series Season 12" was not found but was inferred from the data.
Item set smoldering_journey: Bundle definition "Smoldering Journey" was not found but was inferred from the data.
Item set spelunkers_haul: Bundle definition "Battle of Central Europe Season 3" was not found but was inferred from the data.
Item set tevent_2_gatekeeper_set: Bundle definition "TEvent Dota 2 Season 2" was not found but was inferred from the data.
Item set the_grey_gallant: Bundle definition "The Grey Gallant" was not found but was inferred from the data.
Item set the_iceborn_trinity: Bundle definition "Iceborn Trinity" was not found but was inferred from the data.
Item set tidehunter_tidosaurus: Bundle definition "Dota 2 Canada Cup Season 4" was not found but was inferred from the data.
Item set tine_of_the_behemoth: Bundle definition "Tine of the Behemoth Bundle" was not found but was inferred from the data.
Item set tools_of_final_utterance: Bundle definition "Tools of the Final Utterance" was not found but was inferred from the data.
Item set warhawk_vestiments: Bundle definition "Synergy League Season 1" was not found but was inferred from the data.
Item set warlock_dark_curator: Bundle definition "CEVO Season 6" was not found but was inferred from the data.
Item set wild_tamer_set: Bundle definition "MPGL SEA Season 7 Bundle" was not found but was inferred from the data.
Item set witchdoctor_devilish_conjurer: Bundle definition "joinDOTA MLG Pro League Season 2 Bundle" was not found but was inferred from the data.
Item set writhing_executioner: Bundle definition "Writhing Executioner" was not found but was inferred from the data.
CEntitySystem::BuildEntityNetworking (parallel build of client) took 124.035 msecs for 659 out of 675 classes
Item set lina_fiery_soul_arcana: No bundle definition specified or found.ILocalize::AddFile() failed to load file "Resource/gameui_english.txt".
ILocalize::AddFile() failed to load file "Resource/valve_english.txt".
ILocalize::AddFile() failed to load file "Resource/items_english.txt".
File error loading resource header "panorama/images/textures/startup_background_logo.vtex_c" (Error: ERROR_FILEOPEN)
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_strong.vmat!
Texture g_tNoise doesn't exist in materials/deferred_lights/ssao_med.vmat!
SwitchToLoop levelload requested:  id [1] addons []
8 CPUs (4 physical), Frequency: 2.7 Ghz,  Features: GenuineIntel SSE SSE2 SSE4.1 SSE4.2 AVX MMX RDTSC CMOV FCMOV 
ChangeGameUIState: DOTA_GAME_UI_STATE_INVALID -> DOTA_GAME_UI_STATE_LOADING_SCREEN
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
CSource2Surface::BCreateDeviceResources()
Idle (levelload)
=====================
Initial Connection no
Lobby State -1
Time: 0.0
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
=====================
Initial Connection no
Lobby State -1
Time: 0.0
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
Writing configuration for slot 0
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 
SwitchToLoop game requested:  id [1] addons []
name[ 0 ] changing from 'unnamed' to 'Zyr'
SV:  maxplayers set to 1
Initializing script VM...
...done
CL:  Adding Prequisite CWaitForGameServerStartupPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CCreateGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CConnectGameClientPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadStartupResourcePrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CLoadSpawnGroupsPrerequisite to sequence for CGameClientConnectPrerequisite
CL:  Adding Prequisite CFinalizeConnectionPrerequisite to sequence for CGameClientConnectPrerequisite
Got network config from CDN.  Loaded revision 15 OK
SV:  Spawn Server: <empty>
CL:  CWaitForGameServerStartupPrerequisite done waiting for server
CL:  PS_SATISFIED CWaitForGameServerStartupPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  CCreateGameClientJob creating client connection to 'loopback'
CL:  PS_SATISFIED CCreateGameClientPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  Sending connect to loopback
SV:  Sending S2C_CHALLENGE [2736341519 auth 2] to loopback
CL:  Received S2C_CHALLENGE [2736341519 auth 2] from loopback
CL:  Sending C2S_CONNECT [40 protocol 2736341519 auth 2] to loopback
SV:  Receiving C2S_CONNECT [protocol 40 2736341519 auth 2] from loopback
SV:  Sending S2C_CONNECTION to loopback [addons:'']
SV:  Sending S2C_CONNECTION to loopback [addons:'']
CL:  Received S2C_CONNECTION from loopback [addons:'']
=====================
Initial Connection no
Lobby State -1
Time: 0.0
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
CL:  Connected to 'loopback'
SV:  Sending server info to client 'Zyr' at loopback
SV:  WriteInitialSpawnGroups sending 1 groups
CL:  PS_SATISFIED CConnectGameClientPrerequisite in sequence for CGameClientConnectPrerequisite

Game: "Dota 2"
Map: "<empty>"
Players: 1 (0 bots) / 1 humans
Build: 6817
Server Number: 1

Initializing script VM...
...done
=====================
Initial Connection no
Lobby State -1
Time: 1.2
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
=====================
Initial Connection no
Lobby State -1
Time: 1.2
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
=====================
Initial Connection no
Lobby State -1
Time: 1.2
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
CL:  PS_SATISFIED CLoadStartupResourcePrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CLoadSpawnGroupsPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  PS_SATISFIED CFinalizeConnectionPrerequisite in sequence for CGameClientConnectPrerequisite
CL:  OnStatusFinished for CGameClientConnectPrerequisite
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
SV:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
SV:  Game started
CL:  IGameSystem::LoopActivateAllSystems
SV:  Sending full update to client Zyr (reason:  initial update)
ShouldClientReceiveStringTableUserData called with NULL GameRules() on table userinfo, string 0
CL:  Receiving uncompressed update from server
CL:  CL_ProcessPacketEntities: frame window too big (>=128)
=====================
Initial Connection no
Lobby State -1
Time: 1.3
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
CL:  Signon traffic "client":  incoming 35.935 KB [7 pkts], outgoing 1.125 KB [6 pkts]
NOTE: Not updating item schema.  Using version 5CC203C6; latest version is CC808EA1
Failed to refresh market data: Getting response body data failed
=====================
Initial Connection no
Lobby State -1
Time: 1.8
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
=====================
Initial Connection no
Lobby State -1
Time: 1.8
Abandon: no
Safe to Leave: no
Reconnect: no
Disconnect: no
InReadyUp: no
Returning to Queue: no
=====================
ConVarRef dota_ignore_nonfriend_guild_invites doesn't point to an existing ConVar
defaultfocus=TestContainer not found within layout file for 
Writing configuration for slot 0
Writing configuration for slot 0
Writing configuration for slot 0
] condump
```

**Comment by gdrewb-valve** [comment]
The ILocalize::AddFile errors are why the localized text is not available.  I believe the issue is that they are in 'resource' and not 'Resource'.  That's not an issue on Windows but needs to be fixed for Linux.

**Comment by gdrewb-valve** [comment]
Just to double-check, if you look at your Reborn files on disk these files (valve_english.txt, gameui_english.txt, etc.) should be in the Reborn folder under game/dota_imported/resource.  Are they there?

**Comment by gdrewb-valve** [comment]
The casing is a red-herring, that'll get fixed up, so it seems like you may be missing some files.

**Comment by MaelRL** [comment]
I can find all the files that fail to load in /game/dota_importer_resource (and /game/core/resource for vgui_english.txt).

**Comment by gdrewb-valve** [comment]
That's very strange, I'm not sure why the files wouldn't load if they're present.  What filesystem is in use where your games files are?

If you have time to waste I'd recommend removing Reborn and doing a fresh install but I have no idea if that would help or not.

**Comment by MaelRL** [comment]
File system is ext4. I can try a re-install over the week-end.

**Comment by Kirov123** [comment]
I can try a reinstall today, and post terminal output when it is installed
again.

**Comment by Kirov123** [comment]
I can't seem to copy the terminal output fro some reason, but the output seems very similar to MaeIRL's, including the files that cannot be found. My fliesystem is also ext4. I believe that ext4 is case sensitive, which may be the issue.

**Comment by gdrewb-valve** [comment]
The game will end up using the correct case so I don't think that's the issue.  You are still having the problem after removing Reborn entirely and reinstalling?

**Comment by Kirov123** [comment]
Yes. I tried changing the case of the resource folders to Resource as shown in the terminal and restarting the game, but that did nothing so I changed it back. Im going to validate the cache to see if that fixes anything. Should those files have the names of items in them?

**Comment by gdrewb-valve** [comment]
items_english.txt has most of the item strings.

In theory validating and reinstalling should have no effect since you do have the files on disk, but as there's no reason why they wouldn't get opened the investigation is kind of stuck.  If you have anything out of the ordinary, such as symlinks / NAS / wormoles, that might bear on the problem please let us know.

**Comment by MaelRL** [comment]
Renaming the folders for the correct casing (and restarting Steam/Dota) seems to actually do the trick for me.

I had tried earlier but a small issue is that resource/dota_english.txt and Resource/items_english.txt are requested so it didn't work, but I've now just duplicated the folder to have both options and almost everything loads nicely : only very few item descriptions are still missing (for example for Abbadon's Tarnhelm of Ruin, it still says #DOTA_item_desc_etc.).

**Comment by computerquip** [comment]
Casing appears to be the issue. Setting both "game/dota_imported/resource" and "/game/core/resource" to the correct(?) casing seems to fix the issue for me. 

I could not find an item in my armory that has a missing English description.

**Comment by Kirov123** [comment]
Adding folders with Resource instead of resource in the locations specified by computerquip has fixed the issue for me as well as far as I can see.

**Comment by gdrewb-valve** [comment]
That's good that you've pinned it down but it does leave a mystery as to why the case correction isn't working for you.  The game fixes up the case normally (otherwise everybody running on a case-sensitive filename would have the same issue) and for some reason that doesn't work for you guys.  There aren't a lot of ways that it can fail.  Do you have long paths to where the files are?

**Comment by computerquip** [comment]
Fair point. This is the full path of the folder: "/storage-ssd/SteamLibrary/SteamApps/common/dota 2 beta/game/dota_imported/resource"

storage-ssd is an ext3 filesystem statically mounted from a separate harddrive. It is manually added to any Steam environment I setup after Steam is installed. 

Not sure what it could be.

**Comment by gdrewb-valve** [comment]
Your path isn't long so that isn't the issue.  However, I wonder if it's the other uppercase letters.  There's a fallback in the case correction that just stomps everything to lowercase and that will clearly fail for you.  Looking over the code I see some ways that it would reach that point so I believe that could explain it.  Fixing it shouldn't be a problem.

**Comment by computerquip** [comment]
SteamApps should actually be steamapps now that I think about it. There
were some steam issues with the casing so I soft linked SteamApps to
steamapps.

However, by the sound of it, any other capital letter would also be
crushed. Wouldnt be easier to request the resource in the correct case?

**Comment by Turmfalke2** [comment]
Is there anyway to differentiate between files being used for reborn and files for normal dota? I thought with reborn being so different it would be a completely new folder in SteamApps/common/, but apparently this is not the case.
For me the game also fails to load:
ILocalize::AddFile() failed to load file "Resource/valve_english.txt".
ILocalize::AddFile() failed to load file "Resource/vgui_english.txt".

It looks like generally the game is using a lower case r for resource:
~/.steam/steam/SteamApps/common/dota 2 beta $ find . -type d -iname Resource
./game/dota_lv/resource
./game/dota_imported/resource
./game/dota/resource
./game/dota_addons/hero_demo/resource
./game/dota_addons/overthrow/resource
./game/dota_addons/holdout_example/resource
./game/dota_addons/adventure_example/resource
./game/dota_addons/addon_template/resource
./game/dota_addons/lua_ability_example/resource
./game/dota_addons/tutorial_basics/resource
./game/core/resource
./platform/resource
./dota/resource

Searching for the two mentioned files reveals the following:
~/.steam/steam/SteamApps/common/dota 2 beta $ find . -type f -name valve_english.txt
./game/dota_imported/resource/valve_english.txt
./dota/resource/valve_english.txt
turmfalke@Temperantia ~/.steam/steam/SteamApps/common/dota 2 beta $ find . -type f -name vgui_english.txt
./game/core/resource/vgui_english.txt
./platform/resource/vgui_english.txt
Next I tried adding some soft links for Resource -> resource
ln -s resource game/dota_imported/Resource
ln -s resource dota/Resource
ln -s resource game/core/Resource
ln -s resource platform/Resource

This solved the problem, so yes you found the issue. Also suddenly my hotkey for openging/closing the console works again. I have no idea why not finding localization files would affect the hotkey..

**Comment by gdrewb-valve** [comment]
There's a whole bunch of code developed on Windows where case didn't matter so it may not have the right case.

**Comment by Turmfalke2** [comment]
I am aware of that, but I would assume your design document would specify whether it is supposed to be Resource or resource?

**Comment by gdrewb-valve** [comment]
Unfortunately it's not that simple.  resource is the correct case but it at one point it was Resource and there's still code from that era.  Simple mistakes don't get caught either because either way it works on Windows.

**Comment by Turmfalke2** [comment]
Well, I guess the important thing that we found the issue.
Also is there any reason why we have the same files multiple times? They are not that large, but the cloned folder structure with identical files, feels a bit redundant and makes it unnecessary difficult to figure which file the game is actually trying to read.

**Comment by gdrewb-valve** [comment]
Largely history.  Things should gradually improve but the current duplication is small and so not a high priority.  There's also an override system so files of the same name can be in multiple places but they'll have different content.

**Comment by computerquip** [comment]
>There's a whole bunch of code developed on Windows where case didn't matter so it may not have the right case.

I thought this was an isolated case unfortunately.

For what it's worth, I fixed SteamApps to be steamapps again and it did not work. In this case, if it's still stomping SteamLibrary to lower case, it's definitely a bug since that folder should be able to be named anything.

**Comment by MaelRL** [comment]
Yesterday's patch has fixed most of the include failures except for :
```
 ILocalize::AddFile() failed to load file "Resource/valve_english.txt".
```
Consequently, item names do show up!

 The previous issue I reported with some item descriptions is still happening though, but these descriptions do not exist in items_english.txt (for example, there's no line for ```#DOTA_Item_Desc_Winged_Shroud_of_Ruin```), so I assume the problem is just that if a line can't be found, it prints ```#DOTA_Item_Desc_etc.``` instead of not printing anything at all (like it does in source 1).

**Comment by gdrewb-valve** [comment]
I see that one in items_english.txt.  Do you have any of these?  The file should be something like 12,350 lines.

		"DOTA_Item_Winged_Paladins_Helm"		"Winged Paladin's Helm"
		"DOTA_Item_Winged_Shroud_of_Ruin"		"Winged Shroud of Ruin"
		"DOTA_Item_Wingers_of_the_Arch_Temptress"		"Wingers of the Arch Temptress"

**Comment by MaelRL** [comment]
My file is actually above 14k lines, but you misunderstood my post : the name is showing perfectly, the issue is that if the item has no description (which happens for example for that Abaddon's item; you can check on source 1 or wikis, the item has no description), the game prints the variable name ```#DOTA_Item_Desc_name_of_the_item``` instead of not printing anything at all. See picture below.

![desc_bug](https://cloud.githubusercontent.com/assets/5074170/8396133/39bc59fe-1d99-11e5-815e-a8b02edb2455.png)

It's an issue that it slightly different than the rest of the thread so maybe I should have created a new issue, sorry.

**Comment by Kirov123** [comment]
This looks like the same issue, although the patch appears to have fixed item names. Your descriptions are still messed up though.

**Comment by MaelRL** [comment]
But it's not the same cause. For example, the items_english.txt for source 1 doesn't have an entry for ```#Dota_Item_Desc_Winged_Shroud_of_Ruin``` either, but the source 1 dota 2 will not print the variable, it just leaves the description box empty.

**Comment by gdrewb-valve** [comment]
Ah, sorry I missed the name vs. description part.  This happens on all platforms and I've sent it over the larger team.  It won't be tracked here.
