### ISSUE TITLE
New update Mac force restart while playing dota 2

### ISSUE THREAD

**Issue by jojalapa** [ValveSoftware/Dota-2#1642]
Since the latest update, my mac crash down every time when i open dota2, and it force it to restart.
https://steamcommunity.com/app/570/discussions/0/1644294896728741353/
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes/No]
* Are you using the latest stable video driver available for your system? [Yes/No]
* Have you verified the game files?: [Yes/No]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. open the game
2. press play dota
3. it restarts.

**Comment by kisak-valve** [comment]
Hello @jojalapa, discussion of this already started at #1640. I'm not going to summary close this as a duplicate because there's a chance the opening post's issue on linux may be separate.

**Comment by jojalapa** [comment]
thank you very much.

**Comment by NotInThere** [comment]
Just an update on #1640 updating OS X to 10,13 from 10,11 seems to have resolved the issue. I'm still in the process of queueing and booting into game to see if its completely resolved.

**Comment by ghost** [comment]
Hi,

Any news about this bug ?
(well, more than just a bug, we can't play dota at all for few days now...)

As a lot of concerned people I am on MacOS ElCapitan 10.11.6, and honestly an os update is really not a solution, we need a real fix please. Some can't upgrade because they have old macs, some for compatibility problems, (myself, i have a slow internet and the upgrade to Mojave took me 2 days, i tried it once, installation problem, i need to download it again... yay... -_-)

My system information : 
```
Informations de l'ordinateur :
    Fabricant : Apple
    Modèle : MacBookPro11,4
    Type : Ordinateur portable
    Aucun écran tactile détecté

Processeur :
    Fabricant du CPU : GenuineIntel
    Marque du processeur : Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Famille du processeur : 0x6
    Modèle du processeur : 0x46
    Révision processeur : 0x1
    Type de processeur : 0x0
    Fréquence : 2200 Mhz
    8 processeurs logiques
    4 processeurs physiques
    HyperThreading : Pris en charge
    FCMOV : Non pris en charge
    SSE2 : Pris en charge
    SSE3 : Pris en charge
    SSSE3 : Pris en charge
    SSE4a : Non pris en charge
    SSE41 : Pris en charge
    SSE42 : Pris en charge
    AES : Pris en charge
    AVX : Pris en charge
    CMPXCHG16B : Pris en charge
    LAHF/SAHF : Pris en charge
    PrefetchW : Non pris en charge

Version du système d'exploitation :
    MacOS 10.11.6 (64 bits)

Carte graphique :
    Pilote : Intel Iris Pro
    Version du pilote : 1.2
    Version OpenGL : 2.1
    Profondeur de couleur du bureau : 32 bits par pixel
    Taux de rafraîchissement du moniteur : 0 Hz
    ID fabricant : 0x8086
    ID périphérique : 0xd26
    Révision : 0x8
    Nombre de moniteurs : 1
    Nombre de cartes vidéo logiques : 1
    Résolution de l'affichage principal : 1920 x 1200
    Résolution du bureau : 1920 x 1200
    Taille de l'affichage principal : 12.99" x 8.15" (15.31" diag)
 33.0cm x 20.7cm (38.9cm diag)
    Mémoire vidéo principale : 0 Mo

Mémoire :
    RAM : 16384 Mo

Divers :
    Langue de l'interface : Français
    Type de support : DVD
    Espace disque total disponible : 238208 Mo
    Plus grand bloc disponible sur le disque dur : 73452 Mo
    Casque VR : aucun détecté
```

Here is the most "popular" topic about it on the forum : https://steamcommunity.com/app/570/discussions/0/1644294896726172190/


Thanks for solving it.

**Comment by zuhalm** [comment]
he is right, upgrading os isnot a solution

**Comment by R2NN** [comment]
also have this problem and a lot of people. And I'm asking you to start deciding for a few days I can't play. And it is not possible to upgrade to 10.13 mac os.

**Comment by kotoOo** [comment]
Do we have any progress?

**Comment by dante2608** [comment]
Hi,

For my case, Dota 2 crashed occasionally on Mac OS and the FPS dropped gradually over times until I restarted Steam and Dota 2. It is unable to me for playing ranked match over the past few days.

**Comment by murderousmaria** [comment]
Open Dota, first mouse stops working, everything stops, computer force restarts itself. iMac late 2012 with El Capitan and everything worked really well before this update. 

Someone suggested updating OS in Steam - can't do as Apple did not work with Nvidia to update the screen drivers and new OS versions cause screen ghosting. The moment I'm back on El Capitan, everything works well so I'm not buying a new computer just for Dota or latest OS. Ended my Dota plus sub, due to not knowing if they even are going to fix this issue. 

iMac (27-inch, Late 2012)
Processor 3,2 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3
NVIDIA GeForce GTX 675MX 1024 MB

Your system information

System information https://gist.github.com/murderousmaria/4c950758fae68ae9fc56117352d2168f
Have you checked for system updates?: [Yes/No] Y - see above
Are you using the latest stable video driver available for your system? [Yes/No] Y, see above
Have you verified the game files?: Y

**Comment by mindfreak1200** [comment]
i also have the same problem 
this message shows up:


Anonymous UUID:       138C13B6-09B3-33CD-B9EE-77967FF4EC60

Mon Jul 22 21:59:56 2019

*** Panic Report ***
panic(cpu 1 caller 0xffffff8010b8dd11): "Spinlock acquisition timed out: lock=0xffffff801c0f3520, lock owner thread=0xffffff801e266b60, current_thread: 0xffffff801d51c000, lock owner active on CPU 0x0, current owner: 0xffffff801e266b60"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3248.73.11/osfmk/i386/locks_i386.c:378
Backtrace (CPU 1), Frame : Return Address
0xffffff90ab333d70 : 0xffffff80106dab52 
0xffffff90ab333df0 : 0xffffff8010b8dd11 
0xffffff90ab333f30 : 0xffffff8010b8b564 
0xffffff90ab333f60 : 0xffffff8010c28341 
0xffffff90ab333fb0 : 0xffffff80107ec3f6 

BSD process name corresponding to current thread: dota2

Mac OS version:
15G22010

Kernel version:
Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64
Kernel UUID: 7564B0E7-EB5D-3887-BA79-59C870165AB1
Kernel slide:     0x0000000010400000
Kernel text base: 0xffffff8010600000
__HIB  text base: 0xffffff8010500000
System model name: iMac9,1 (Mac-F2218FC8)

System uptime in nanoseconds: 1069038849808
last loaded kext at 582672243801: com.devguru.driver.SamsungACMData	1.4.32 (addr 0xffffff7f93279000, size 86016)
last unloaded kext at 994639664502: com.devguru.driver.SamsungComposite	1.4.32 (addr 0xffffff7f93222000, size 16384)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.0.10
org.virtualbox.kext.VBoxNetFlt	5.0.10
org.virtualbox.kext.VBoxUSB	5.0.10
org.virtualbox.kext.VBoxDrv	5.0.10
com.netease.nemu.kext.NemuDrv	15.2.97
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AGPM	110.22.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHDA	274.12
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	4.4.6f4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleLPC	3.1
com.apple.GeForceTesla	10.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.4.6f4
com.apple.driver.AppleMikeyDriver	274.12
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleBacklight	170.8.9
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.AppleIRController	327.6
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	38
com.apple.iokit.SCSITaskUserClient	3.7.7
com.apple.iokit.IOAHCIBlockStorage	2.8.5
com.apple.driver.AppleFWOHCI	5.5.4
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.driver.usb.AppleUSBOHCIPCI	1.0.1
com.apple.driver.AppleAHCIPort	3.1.8
com.apple.nvenet	2.0.22
com.apple.driver.usb.AppleUSBEHCIPCI	1.0.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	4.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	4.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	163
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.AppleGraphicsDeviceControl	3.12.9
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	274.12
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOSurface	108.3.2
com.apple.iokit.IOSerialFamily	11
com.apple.driver.CoreCaptureResponder	1
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	274.12
com.apple.iokit.IOHDAFamily	274.12
com.apple.iokit.IOAudioFamily	204.4
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.4.6f4
com.apple.iokit.IOBluetoothFamily	4.4.6f4
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.nvidia.classic.NVDAResmanTesla	10.0.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d7
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.usb.AppleUSBHub	1.0.1
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.0.1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.0.1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.7
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOAHCISerialATAPI	2.6.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.7
com.apple.iokit.IOFireWireFamily	4.6.1
com.apple.iokit.IO80211Family	1110.26
com.apple.driver.corecapture	1.0.4
com.apple.driver.usb.AppleUSBOHCI	1.0.1
com.apple.iokit.IOAHCIFamily	2.8.1
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.usb.AppleUSBEHCI	1.0.1
com.apple.driver.NVSMU	2.2.9
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.0.1
com.apple.driver.AppleUSBHostMergeProperties	1.0.1
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	417.4
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	4.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: iMac9,1, BootROM IM91.008D.B08, 2 processors, Intel Core 2 Duo, 2.66 GHz, 4 GB, SMC 1.37f3
Graphics: NVIDIA GeForce 9400, NVIDIA GeForce 9400, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334448312D4346382020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334448312D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 4.4.6f4, 3 services, 19 devices, 3 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: WDC WD6400AAKS-40H2B0, 640.14 GB
Serial ATA Device: HL-DT-ST DVDRW  GA11N
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: USB Bus
USB Device: USB Keyboard
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Bus
USB Device: IR Receiver
USB Device: Usb Mouse
Thunderbolt Bus:

**Comment by murderousmaria** [comment]
I really hope we could get a fix for this as the Reddit and Steam forums are getting heated. People pay for battlepass and Dota plus and can't play at all. 159 comments on one Steam community topic: https://steamcommunity.com/app/570/discussions/0/1644294896726172190/

**Comment by iwini** [comment]
No,it's not better,it's still exist.
https://steamcommunity.com/app/570/discussions/0/1644294896726172190/
The topic has 12 pages now. 
Please fix it.

**Comment by R2NN** [comment]
We would like to know at least how long the problem will be and whether it is corrected at all

**Comment by wheublein** [comment]
I have also experienced repeated system crash on OSX. Similar panic report to above:

> *** Panic Report ***
> panic(cpu 1 caller 0xffffff8008f8dd11): "Spinlock acquisition timed out: lock=0xffffff8034489138, lock owner thread=0xffffff802d820240, current_thread: 0xffffff802a0bf000, lock owner active on CPU 0x0, current owner: 0xffffff802d820240"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3248.73.11/osfmk/i386/locks_i386.c:378
> Backtrace (CPU 1), Frame : Return Address
> 0xffffff91f3e5bd70 : 0xffffff8008adab52 
> 0xffffff91f3e5bdf0 : 0xffffff8008f8dd11 
> 0xffffff91f3e5bf30 : 0xffffff8008f8b564 
> 0xffffff91f3e5bf60 : 0xffffff8009028341 
> 0xffffff91f3e5bfb0 : 0xffffff8008bec3f6 
> 
> BSD process name corresponding to current thread: dota2
> 
> Mac OS version:
> 15G22010
> 
> Kernel version:
> Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64

**Comment by Once1212** [comment]
Still crashes the system right on startup of the game (half a second in main menu). The game is up to day to 24 Jul.

OSX 10.11.6, no system updated for that anymore, stable system.
NVIDIA Drivers are up to date 346.03.15f09

Verifying the game files does nothing.

**Comment by sherb2k** [comment]
Still down for me too any update.

If this is how you guys stop servicing people on older macs that would be a shame. League of legends gave like a couple months advance update on not supporting older mac osx

**Comment by addyboy08** [comment]
> Since the latest update, my mac crash down every time when i open dota2, and it force it to restart.
> https://steamcommunity.com/app/570/discussions/0/1644294896728741353/
> 
> #### Your system information
> * System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
> * Have you checked for system updates?: [Yes/No]
> * Are you using the latest stable video driver available for your system? [Yes/No]
> * Have you verified the game files?: [Yes/No]
> 
> #### Please describe your issue in as much detail as possible:
> Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).
> 
> #### Steps for reproducing this issue:
> 1. open the game
> 2. press play dota
> 3. it restarts.

![Screen Shot 2019-07-25 at 1 51 06 AM](https://user-images.githubusercontent.com/53319203/61913031-b4c98300-aef0-11e9-9f8f-06079cd67f97.png)
here's the info about my Mac. I have the same problem.

**Comment by sherb2k** [comment]
any update?

**Comment by murderousmaria** [comment]
Got very bad service from Valve support, first of all, they did not read my original message but we're asking again for screenshots when the situation happens, taking a screenshot while your computer forces to restart kinda stops you taking screenshots... sigh. Next, I explained again what happened, and that I had delivered already all the requested stuff here and to the support and that the issue is not just me but various users. This is what I got back. Facepalm. 

"
Thanks for providing this update. I understand that you're still encountering difficulties with Dota on your MacOS.  

If you've gone through the support articles that you've provided in the previous messages with no resolve, **then your next step is to get in touch with a Mac specialist who can have direct access to your machine.**

We apologize if this is not the resolution that you may have been looking for. 

We have provided all the available information in our previous message. Since there's not much more that I can say or do to be of help with this particular issue, I am going to close this help request.

If you have questions on an unrelated issue, please create a new help request and we will be happy to help you. 

Cheers,	
Ollie"

**Comment by thinhlvv** [comment]
Same issue here.
- I tried with reinstalling steam. (Removed steam + Library and download again)
- Reinstall my Mac with removed hard disk.
The issue's still there :(

**Comment by amgorb** [comment]
same issue, bootcamp as temp solution.

**Comment by cdtapay** [comment]
> same issue, bootcamp as temp solution.

hi @amgorb , what you mean by 'bootcap as temp solution'?

**Comment by thinhlvv** [comment]
Solved.
Updated Mac OS to Mojave and works smoothly.

**Comment by kencytbb** [comment]
> Solved.
> Updated Mac OS to Mojave and works smoothly.

It only for new macbook, It wasn't for the old mac

**Comment by jojalapa** [comment]
has already been 2 weeks when i posted this, valve seems they don't care.
valve update the contents on steamwebsite if you are not going to update what is happening.
MINIMUM:
OS: OS X Mavericks 10.9 or newer
Processor: Dual core from Intel
Memory: 4 GB RAM
Graphics: nVidia 320M or higher, or Radeon HD 2400 or higher, or Intel HD 3000 or higher
Network: Broadband Internet connection
Storage: 15 GB available space

**Comment by sherb2k** [comment]
Anonymous UUID:       315BE0BA-B942-085C-EABA-8A5B35ACA43C

Tue Jul 30 22:56:33 2019
Panic(CPU 1): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff80325e5dd8, spinlock owner: 0xffffff8027da9000, current_thread: 0xffffff8027da9000, spinlock_owner_cpu: 0x1
RAX: 0xffffff80325e9d38, RBX: 0x0000000000000001, RCX: 0xffffff80325e9d28, RDX: 0xffffff80325e9d28
RSP: 0xffffff80c5fc3ec0, RBP: 0xffffff80c5fc3f70, RSI: 0xffffff80325e9d70, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff80c5fc3dd0, R11: 0x0000000000000030
R12: 0x0000000000000000, R13: 0xffffff80325e9d28, R14: 0xffffff80325e5dd0, R15: 0xffffff80325e5dd0
RFL: 0x0000000000000286, RIP: 0xffffff80171c7508, CS:  0x0000000000000008, SS:  0x0000000000000000
Backtrace (CPU 1), Frame : Return Address
0xffffff80c00f9f50 : 0xffffff8016ee2cc1 
0xffffff80c00f9f80 : 0xffffff8016edc05f 
0xffffff80c00f9fd0 : 0xffffff8016ef4649 
0xffffff80c5fc3f70 : 0xffffff80171c7a50 
0xffffff80c5fc3fb0 : 0xffffff8016ed7c67 

BSD process name corresponding to current thread: dota2

Mac OS version:
13F1911

Kernel version:
Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64
Kernel UUID: 8926E512-6714-34FC-B27C-6AE90EB51D5E
Kernel slide:     0x0000000016c00000
Kernel text base: 0xffffff8016e00000
System model name: MacBook5,1 (Mac-F42D89C8)

System uptime in nanoseconds: 2310443978994
last loaded kext at 55762382405: com.apple.driver.AudioAUUC	1.60 (addr 0xffffff7f98562000, size 28672)
last unloaded kext at 217184347552: com.apple.driver.AppleFileSystemDriver	3.0.1 (addr 0xffffff7f974c0000, size 8192)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	6.0.6
org.virtualbox.kext.VBoxNetFlt	6.0.6
org.virtualbox.kext.VBoxUSB	6.0.6
org.virtualbox.kext.VBoxDrv	6.0.6
com.apple.driver.AudioAUUC	1.60
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.iokit.IOUserEthernet	1.0.0d1
com.apple.iokit.IOBluetoothSerialManager	4.2.7f5
com.apple.driver.AppleUpstreamUserClient	3.5.13
com.apple.driver.AGPM	100.14.34
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.GeForceTesla	8.2.4
com.apple.driver.AppleHDA	2.6.3f7
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleMikeyDriver	2.6.3f7
com.apple.driver.AppleBacklight	170.4.11
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.2.7f5
com.apple.driver.AppleSMCLMU	2.0.4d1
com.apple.driver.AppleHWAccess	1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleLPC	1.7.0
com.apple.driver.AppleMCCSControl	1.2.5
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleIRController	325.7
com.apple.iokit.SCSITaskUserClient	3.6.7
com.apple.driver.XsanFilter	404
com.apple.BootCache	35
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeLZVN	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.iokit.IOAHCIBlockStorage	2.6.0
com.apple.driver.AirPort.Brcm4331	700.20.22
com.apple.driver.AppleUSBHub	683.4.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleAHCIPort	3.0.5
com.apple.nvenet	2.0.21
com.apple.driver.AppleUSBEHCI	660.4.0
com.apple.driver.AppleUSBOHCI	656.4.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleACPIButtons	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	2.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	217.92.1
com.apple.security.quarantine	3
com.apple.nke.applicationfirewall	153
com.apple.driver.AppleIntelCPUPowerManagement	217.92.1
com.apple.iokit.IOSurface	91.3
com.apple.iokit.IOSerialFamily	10.0.7
com.apple.AppleGraphicsDeviceControl	3.6.22
com.apple.iokit.IOBluetoothFamily	4.2.7f5
com.apple.nvidia.classic.NVDANV50HalTesla	8.2.4
com.apple.nvidia.classic.NVDAResmanTesla	8.2.4
com.apple.driver.DspFuncLib	2.6.3f7
com.apple.vecLib.kext	1.0.0
com.apple.iokit.IOAudioFamily	1.9.7fc2
com.apple.kext.OSvKernDSPLib	1.14
com.apple.driver.AppleBacklightExpert	1.0.4
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.2.7f5
com.apple.driver.AppleHDAController	2.6.3f7
com.apple.iokit.IOHDAFamily	2.6.3f7
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.IOPlatformPluginFamily	5.7.1d6
com.apple.driver.AppleSMBusController	1.0.12d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleSMC	3.1.8
com.apple.kext.triggers	1.0
com.apple.driver.AppleUSBMultitouch	240.10
com.apple.iokit.IOUSBHIDDriver	660.4.0
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.6.7
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.driver.AppleUSBMergeNub	650.4.0
com.apple.driver.AppleUSBComposite	656.4.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.6.7
com.apple.iokit.IO80211Family	640.36
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOUSBUserClient	660.4.2
com.apple.iokit.IOAHCIFamily	2.6.5
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOUSBFamily	686.4.1
com.apple.driver.NVSMU	2.2.9
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.TMSafetyNet	7
com.apple.security.sandbox	278.11.2
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOReportFamily	23
com.apple.driver.DiskImages	373
com.apple.iokit.IOStorageFamily	1.9
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	2.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
panic(cpu 0 caller 0xffffff80171c65b5): "Spinlock acquisition timed out: lock=0xffffff80325e5dd8, lock owner thread=0xffffff8027da9000, current_thread: 0xffffff8027ed5140, lock owner active on CPU 0x1, current owner: 0xffffff8027da9000"@/SourceCache/xnu/xnu-2422.115.15/osfmk/i386/locks_i386.c:365
Backtrace (CPU 0), Frame : Return Address
0xffffff80c675bd90 : 0xffffff8016e23139 
0xffffff80c675be10 : 0xffffff80171c65b5 
0xffffff80c675bf20 : 0xffffff80171c64c4 
0xffffff80c675bf50 : 0xffffff8017241983 
0xffffff80c675bfb0 : 0xffffff8016ef4c86 

BSD process name corresponding to current thread: dota2
Model: MacBook5,1, BootROM MB51.007D.B03, 2 processors, Intel Core 2 Duo, 2 GHz, 5 GB, SMC 1.32f8
Graphics: NVIDIA GeForce 9400M, NVIDIA GeForce 9400M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142323837344448312D4346382020
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1067 MHz, 0x830B, 0x4E54344743363442384847304E532D444920
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WD2500BEVT-00ZCT0, 250.06 GB
Serial ATA Device: HL-DT-ST DVDRW  GS21N
USB Device: USB OPTICAL MOUSE
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Built-in iSight
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
Thunderbolt Bus: 

still happening

same issue as everyone else and my thread that got closed

**Comment by amgorb** [comment]
seems that Valve developers is about to discover what regression testing really means.

**Comment by ohh-v2** [comment]
Is this problem still happening?

On the morning of Tuesday 30 July, I was still unable to play. I was offline traveling for the next few days, and last night (Friday 2 August) I tried Dota again. After Steam loaded the past couple of days of updates, the game suddenly worked fine.

This morning I've tried Dota on three sets of hardware (early 2009 iMac, mid-2010 MacBook Pro, mid-2009 MacBook - you can guess when we became a Mac household), all running OSX 10.11.6, and Dota's running fine on all of 'em.

I'd like to know if anyone is still having the original problem, or if one of the recent patches solved it for everybody. If it *has* magically cured itself, we can probably close the issue.

**Comment by murderousmaria** [comment]
> Is this problem still happening?
> 
> On the morning of Tuesday 30 July, I was still unable to play. I was offline traveling for the next few days, and last night (Friday 2 August) I tried Dota again. After Steam loaded the past couple of days of updates, the game suddenly worked fine.
> 
> This morning I've tried Dota on three sets of hardware (early 2009 iMac, mid-2010 MacBook Pro, mid-2009 MacBook - you can guess when we became a Mac household), all running OSX 10.11.6, and Dota's running fine on all of 'em.
> 
> I'd like to know if anyone is still having the original problem, or if one of the recent patches solved it for everybody. If it _has_ magically cured itself, we can probably close the issue.

Thank you! It seems to work, I didn't try in the past couple days as it always crashed the computer and I lost my hope but today - it finally runs!

**Comment by addyboy08** [comment]
It’s all good now, thank God.

**Comment by danginsburg** [comment]
Yes, we pushed an update to resolve the issue on macOS 10.11.

**Comment by kisak-valve** [comment]
Closing as fixed.
