### ISSUE TITLE
Cannot click on most of the buttons after MacOS launch fix patch. 

### ISSUE THREAD

**Issue by umang-desai** [ValveSoftware/Dota-2#1750]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/umang-desai/d30620c7d128499c0779ab5f39b8d7ac
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
After the MacOS game launch patch fix, I am able to open the game but I can only click on buttons in the top left quadrant. 

Think of it as a graph. 4 quadrants. Can only click on the top left. Also, when I click in other areas, it opens stuff which is in the first quadrant. So it will open the battlepass menu(whose button is also in first quadrant).

https://ibb.co/kSxTW8q

I have show which quadrant works and doesnt work in the image above. 

#### Steps for reproducing this issue:

1. Launch Dota 2 on Mac. 
2. Click on different quadrants.

**Comment by umang-desai** [comment]
Update:

I am able to click on buttons now. I dont know if the update solved the issue or not, but I think the main problem was that when the game was using my "Use my monitors resolution", it set it to 3360 x 2100. When my monitor resolution is 1680 x 1050. 

I noticed this when I set my video setting to the smallest resolution and was able to click all buttons. I hope this helps someone else with the same issue.

I think it happened to me because I also use another big screen for work. But I dont know why dota picked that screen up since it wasnt even connected to my machine and I had also reinstalled dota and restarted my machine all while the external display WAS NOT connected.

**Comment by danginsburg** [comment]
There is a real bug here, reopening.  I'm able to repro this with desktop friendly fullscreen on Macbook Pro (Mid 2012) where at 2800x1800 only one quarter of the screen is clickable.  Looking into it.

**Comment by danginsburg** [comment]
I've got a fix for this one, should be incoming in a future update.  For retina modes you'll need to use exclusive fullscreen (as with previous versions of Dota).  The fix will take care of the incorrect desktop friendly fullscreen resolutions being available which was a regression.

**Comment by umang-desai** [comment]
Great. Thanks @danginsburg. This should fix it for when I play on my extended screen. 

Cheers!

**Comment by emmc89** [comment]
@danginsburg it's still not working properly. Desktop friendly fullscreen is not blocking the screen in dota like before. Also when the game starts in exclusive fullscreen the screen become black.

I'm testing in Catalina OS 2560 x 1600 Retina

**Comment by danginsburg** [comment]
@emmc89 please open another bug with the details of your issue and complete system information.  You seem to be reporting two things: 1) that exclusive fullscreen is full black (are you sure you waited long enough for the game to load?) and 2) something about "not blocking the screen in dota like before" which I need more details on.  I believe I fixed the bug @umang-desai  reported so I need more info.
