### ISSUE TITLE
Dota crashing on MacOSX After Windrunner update.

### ISSUE THREAD

**Issue by GiteshKhanna** [ValveSoftware/Dota-2#1824]
#### Your system information
* System information from steam (`Steam` -> `Help` -> `System Information`) : [gist](https://gist.github.com/GiteshKhanna/a47eb6023b041a4e50cc5443fcafd72b )
* Have you checked for system updates? Yes
* Are you using the latest stable video driver available for your system?  Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
After the windrunner update, Dota crashing after hero selection is finished and load up screen comes. There are no crash errors displayed. I tried reconnecting but again the game crashes. Game working perfectly fine in custom lobby and spectating.

#### Steps for reproducing this issue:

1. Find Match. [I tried ranked.]
2. Select Hero.
3. Wait for timer for game to start.

**Comment by bergmannf** [comment]
I have the exact same issue on Linux (Fedora) - [System Information](https://gist.github.com/bergmannf/08ec2cdda5678e5b13487ea16b8234dc)

**Comment by yunstanford** [comment]
+1 same issue on Mac.

**Comment by maxence33** [comment]
Same here on Ubuntu 18.10

When clicking reconnect, game crashed. I saw the "reconnect button" for about 20 minutes. So some players might be playing while I tried to connect

**Comment by tvelich** [comment]
It crashed for me during picks and kept crashing on any reconnect attempts. The match I was in just ended and the game also crashes when you try to open the scoreboard although other match scoreboards load fine still.

Edit: Running Linux Mint 19.3

**Comment by danginsburg** [comment]
We're having trouble reproducing this crash.  If anyone finds a set of reproducer steps please post it here.

**Comment by aj-yh** [comment]
@danginsburg I've been able to reproduce this bug multiple times on MacOS 10.13.6, with slight different variations in outcome. 

When picking Unranked: All Pick, I'll make it through the pick phase but will be unable to join the game. 
- In once instance, after the loading screen, I was immediately returned to the home screen, and given the option to reconnect. On trying to do so I was again returned to the home screen. 
- In the other instance, after the picking phase and loading screen, the game entirely crashed. On rerunning the game after restarting my computer, I was again got the reconnect option, but when doing so, the game would crash again.

Here's my system info from Steam: https://pastebin.com/dgJiGvta

**Comment by kajborjeson** [comment]
It crashes reliably when trying to load Spectre.
Steps to reproduce: Start game, click Heros, click Spectre.

**Comment by tvelich** [comment]
> It crashes reliably when trying to load Spectre.
> Steps to reproduce: Start game, click Heros, click Spectre.

Good catch, I just even tried to view Spectre in the heroes menu and my game crashed

**Comment by iridian-ks** [comment]
I'm running the latest elementaryOS.

The game also instantly crashed after the windrunner update for me.

I tried switching to -vulkan as well as a few other flags: -high -map dota -prewarm

Without those flags the game instantly crashed right after character selection on Turbo. After setting those flags and switching graphics to lowest I was able to join, but the game was unbearably slow. I tried running a bot game and everything is just fine there.

Another thing I noticed was the hero info cards on character select also seemed broken? Not sure if anyone saw that as well.

https://pastebin.com/iSJVGdYG

**Comment by tvelich** [comment]
> It crashes reliably when trying to load Spectre.
> Steps to reproduce: Start game, click Heros, click Spectre.

Selecting Crystal Maiden is crashing the game for me as well

**Comment by AlvesThales** [comment]
> > It crashes reliably when trying to load Spectre.
> > Steps to reproduce: Start game, click Heros, click Spectre.
> 
> Selecting Crystal Maiden is crashing the game for me as well

Exactly the same for me, and I am using Linux Ubuntu 18.04.5

**Comment by danginsburg** [comment]
Thanks all - got it repro'd and investigating.

**Comment by jstolt3** [comment]
Of interest, I have also had a reproducible problem when playing the Aghanims mode. Twice the game crashed with no message directly before Depth 7 as I was entering the room. Both instances happened at the exact same location. Friends on Windows had no problems. Attempting to reconnect results in immediate crash thereafter. OSX 10.14.6.

**Comment by bhas2797** [comment]
I have the same issue too. I'm using macOS 10.14.2 and every time after the hero pick phase, the game will crash. And when I restart the game , I get a message saying the coordinator is slow to respond , and the process repeats everytime i try to reconnect to my game. Ultimately , I had to abandon the game.
I also tried spectating a few games and this also caused the game to crash for me.

**Comment by danginsburg** [comment]
Fix for the macOS crash is incoming.

**Comment by korrasami** [comment]
When will this fix be released?

**Comment by kushwiz** [comment]
Works if i use Vulcan rendering engine on OSX.
Settings -> video -> Choose Vulcan -> Restart Dota

**Comment by korrasami** [comment]
@kushwiz doesnt work for me, crashes when click Spectre on hero screen.

**Comment by yunstanford** [comment]
how can such serious bug exist in prod for such long time ? lol

**Comment by nero593** [comment]
As usual valve taking a shit on us. When will the fix be deployed

**Comment by steakscience** [comment]
Yup just got an abandon. Thanks for your awesome QA

If you tested even once, you would realize that this can be reproduced 100% of the time after every pick phase.

**Comment by Ho7el** [comment]
Twice today... I fucking grinded my way out of low priority just to be hit with another crash after pick phase in a ranked game. 

Is there ANY WAY to take off penalties for this bullshit crash bug?

I have to wait 3 hours to play and I get to fucking dig out of low prio again.

**Comment by sajagshrestha** [comment]
got banned cause of this. :(

**Comment by GiteshKhanna** [comment]
Thanks for working on this @danginsburg . Please do post here once the release is sent. I can already see an update, but still the issue prevails.

**Comment by TheGP** [comment]
Same Macbook pro, Catalina. Happened in Agh's lab

**Comment by adrianhihi** [comment]
Same Macbook Pro here, every time when I tried to watch a friend's game live or tried to start a game, the Dota will be crushed and force me to quit immediately.

**Comment by GiteshKhanna** [comment]
@adrianhihi  I think it's an issue with a few heroes. Try watching a game without spectre and check?

**Comment by xlanor** [comment]
> > It crashes reliably when trying to load Spectre.
> > Steps to reproduce: Start game, click Heros, click Spectre.
> 
> Selecting Crystal Maiden is crashing the game for me as well

Encountering this issue on Catalina.

No, Vulkan doesn't help either. CM or Spec kills the game for me

**Comment by adrianhihi** [comment]
> @adrianhihi I think it's an issue with a few heroes. Try watching a game without spectre and check?

Yea, you are right, I can watch the game which without spectre, but that is so weird.....

**Comment by sjdilorenzo** [comment]
Same problem here. Happened on ranked game, first game after the update. Then worked well for 2 games and now again. Im in low pr a lost 50 mmr because pf this

**Comment by KaixinDing** [comment]
Same problem here. Select hero, wait for counting down and then game crash. I also find this problem is related to some specific heros, for example I also can't watch a game including spectre.

**Comment by Perc-on1** [comment]
MacOS Catalina user here. 
Switching to Vulkan worked for me so far. Will further update, if I encounter another crash.

**Comment by iL00p** [comment]
Switching to vulkan worked for me too.

**Comment by GiteshKhanna** [comment]
@iL00p  try picking spectre with vulkan on. It won't work I guess.

**Comment by kushwiz** [comment]
If Vulkan doesnt work, check the following:
Open Dota 2 properties from steam library
Click DLC tab
Check the Dota 2 - Vulkan support

Hope this works

**Comment by iL00p** [comment]
@GiteshKhanna It's working for me. I picked spectre, CM and KOTL in demo mode and the game didn't crash. I also looped through all the heroes and nothing happened. Going to try out a Aghs match before trying a real match.

**Comment by maxence33** [comment]
The update this morning (Paris time) is working for me. Also I sudo apt vulkan and added it in DLC.

**Comment by GiteshKhanna** [comment]
Yes vulkan worked for me as well. Also, got a significant performance boost with it !

**Comment by maxence33** [comment]
I think I was using the Vulkan shaders before. As it kinda loaded the shaders before launch. This morning update has probably fixed something.

**Comment by sajagshrestha** [comment]
It still crashes on OpenGL

**Comment by maxence33** [comment]
I thinlk I have been too fast to say it was fixed. 
I did un unranked game and it worked. Yet when I open the list of recent games on my profile and double click on the yesterday's game that I could not take part in, the game crashes. It can't show the result of the game without crashing.
Very funny

**Comment by alandwiprasetyo** [comment]
same here, i lost my MMR twice game because the game crashes.. sample match Match ID : 5599942680 and 5600521818(wrath king)
[system info](https://gist.github.com/alandwiprasetyo/516184f1d56e585672e8ee2317584a79)

**Comment by spawn92** [comment]
This issue still persists . I had a force abandon yesterday and one more just now.  
Unable to even see the game details of abandoned games as client crashes when I try to open it. 
I am even unable to spectate random Labyrinth Games. 

Just to add to the already info - My game client consistently crashes if i try to view Immortal Treasure 1. 
Attaching system info if it is of any help - [gist](https://gist.github.com/spawn92/f85438037d251a2cbbe9391c5435db46)

**Comment by TheGP** [comment]
I can see the replay with the last run of Agh's lab with Vulkan, with OpenGL it crushes.

**Comment by ayz24** [comment]
Qued up for one game, forced abandon, 30 minute penalty. Then got and successfully played a game. Qued for a third and forced abandon, 2 hour penalty, and currently in LP (need to win 4 matches).

When the bug is fixed, will the LP be lifted? I don't want to play those matches if the status will be fixed... Also, easily reproduced by going to all matches and trying to see the details of one of the forced-abandoned ones.

**Comment by m-irfan** [comment]
> Of interest, I have also had a reproducible problem when playing the Aghanims mode. Twice the game crashed with no message directly before Depth 7 as I was entering the room. Both instances happened at the exact same location. Friends on Windows had no problems. Attempting to reconnect results in immediate crash thereafter. OSX 10.14.6.

I am having same issue on entering this depth always, i have even tried clearing downloads cache, verify files integrity, and even reinstalled the game :(
but the issue is still there
Also this crash happening when i play turbo and picked zeus, then before even waiting screen the game crashed. then i was unable to reconnect coz game crashing every time i try reconnect.

**Comment by m-irfan** [comment]
This is my Friend ID in dota 79319232, if any helpful to you to trace out crash logs.
and this is my username on steam "raoirfananwar" if helpful. 
Thanks

**Comment by raviprasadmr** [comment]
> We're having trouble reproducing this crash. If anyone finds a set of reproducer steps please post it here.

Yesterday EG was playing against Alliance in omega league, and RTZ picked Spectre. As soon as it was picked, Dota2 crashed. I could watch other games where Spectre is not being played, but not that game. I cannot even open Spectre in heroes tab.

Vulkan support DLC did not work for me. Vulkan rendering did not work for me either.

**Comment by monkeyphysics** [comment]
> Fix for the macOS crash is incoming.

@danginsburg : please tell me this includes correcting the registered abandons, losses/mmr and behaviour score loss?

**Comment by alandwiprasetyo** [comment]
> > Fix for the macOS crash is incoming.
> 
> @danginsburg : please tell me this includes correcting the registered abandons, losses/mmr and behaviour score loss?

+1 @danginsburg

**Comment by luminkhant** [comment]
I am currently having the same error. Morning update didn't help me. When will the new update be roll out?

**Comment by muoitranduc** [comment]
Here is the temporary fix that helps me play the game (have to play Low Priority as a punishment though):
1) Change video settings to Vulkan
2) Make sure DLC Vulkan is downloaded
3) Put ```-vulkan``` to Steam's "Set Launch Options..."
4) Restart the game

**Comment by arxra** [comment]
Thanks for prioritizing this!
Would be great if 

 - There was a feature to warn users that their OS has instabilities atm
- Not nuke folks behavior score when they try to play a game and it crashes.

But most importantly it's getting fixed in a timely manner, which it seems to get even on a weekend considering your response. 
Doesn't seem like the "launch with vulkan" fix works for linux users, but I'm sure the fix is related and will help!

**Comment by ayz24** [comment]
ETA on the fix?

**Comment by danginsburg** [comment]
The update that fixes the macOS OpenGL crash just shipped.  Thanks for your patience, it was supposed to ship last night but there was a delay.

For all of those working around it using Vulkan: in general I'd recommend continuing to use the Vulkan version over OpenGL.  It has better performance and once your shader cache is warmed it will have less stutters.  In OpenGL on macOS because there is no support for GL_ARB_get_program_binary the OpenGL version suffers very badly from stutters.  We only keep shipping the OpenGL version because some people playing Dota are not on Metal-capable Macs.

Finally - this fix was very specifically for macOS OpenGL.  If you are encountering other crashes on macOS or Linux, please open another issue.  If you have a reliable repro and can provide the steps that greatly increases the chances we can get it fixed quickly.

**Comment by ayz24** [comment]
Is there a chance you can address LP caused as a result of this bug? Doesn't seem to make sense that we are now unable to que for ranked match-making due to the bug..

**Comment by Sumukhsharma** [comment]
I do believe that Low priority from crashed games have been reversed. Not totally sure though.

**Comment by ayz24** [comment]
Yes they have. Thank you thank you!

**Comment by danginsburg** [comment]
> Is there a chance you can address LP caused as a result of this bug? Doesn't seem to make sense that we are now unable to que for ranked match-making due to the bug..

Yes.  We have cleared LP.  I’m going to close this bug.  If people hit other crashes please open up new bugs.

**Comment by alandwiprasetyo** [comment]
> > Is there a chance you can address LP caused as a result of this bug? Doesn't seem to make sense that we are now unable to que for ranked match-making due to the bug..
> 
> Yes. We have cleared LP. I’m going to close this bug. If people hit other crashes please open up new bugs.

but abandoned the game because of this bug be returned MMR too? @danginsburg

**Comment by monkeyphysics** [comment]
> The update that fixes the macOS OpenGL crash just shipped. Thanks for your patience, it was supposed to ship last night but there was a delay.
> 
> For all of those working around it using Vulkan: in general I'd recommend continuing to use the Vulkan version over OpenGL. It has better performance and once your shader cache is warmed it will have less stutters. In OpenGL on macOS because there is no support for GL_ARB_get_program_binary the OpenGL version suffers very badly from stutters. We only keep shipping the OpenGL version because some people playing Dota are not on Metal-capable Macs.
> 
> Finally - this fix was very specifically for macOS OpenGL. If you are encountering other crashes on macOS or Linux, please open another issue. If you have a reliable repro and can provide the steps that greatly increases the chances we can get it fixed quickly.

Vulkan should be made default. I was only on OpenGL because the install defaulted to it. It's strange that I have to enable/download a "DLC", and then go to settings to change the launch flag. All that work to get away from the legacy OpenGL.

**Comment by tvelich** [comment]
> Finally - this fix was very specifically for macOS OpenGL. If you are encountering other crashes on macOS or Linux, please open another issue. If you have a reliable repro and can provide the steps that greatly increases the chances we can get it fixed quickly.

@danginsburg This appears to have fixed it on Linux Mint OpenGL for me

**Comment by steakscience** [comment]
@monkeyphysics While Vulkan is more performant, I think OpenGL is probably still the default because it is less buggy. You will see quite a few issues with particles while playing with Vulkan
