### ISSUE TITLE
Dota 2 Mac OS Game unplayable after patch 7.31 fog of war BUG

### ISSUE THREAD

**Issue by d2ae** [ValveSoftware/Dota-2#2027]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [https://gist.github.com/d2ae/016f08935833cddd421891dce5643f1b#file-gist]: https://gist.github.com/d2ae/016f08935833cddd421891dce5643f1b#file-gist
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I'm playing Dota 2 on Mac OS. In any Dota 2 Game the whole map is and stays dark as if there is fog of war all over the map. Even wards don't give vision, except on the the mini map where the distance of the vision given by the ward is shown right.

There are multiple reports on this issue over different communities:

https://steamcommunity.com/app/570/discussions/0/3187989920099349694/

https://steamcommunity.com/app/570/discussions/0/3187989920100299892/

https://steamcommunity.com/app/570/discussions/0/3187989920102448882/

https://www.reddit.com/r/DotA2/comments/t0jkd0/dota_731_update_map_is_dim_unplayable/

https://www.reddit.com/r/DotA2/comments/t1tom3/my_friend_whos_been_playing_on_mac_got_this_issue/

#### Steps for reproducing this issue:

1. Launch Dota 2
2. Start any game

**Comment by d2ae** [comment]
Another report of this issue with visualized effect of this bug:

https://www.reddit.com/r/DotA2/comments/t0xy2v/map_is_always_dark_in_patch_731_mac_os/

**Comment by d2ae** [comment]
Hello @kisak-valve, any help please for all Dota 2 Mac OS players ? Thank you.

**Comment by d2ae** [comment]
Hello ? Anyone her from Valve still active in this Community and ready to help, please ?
@tycho @bgilmore @Plagman @danieljennings @charleslvalve @danginsburg

**Comment by Quix051** [comment]
up

**Comment by Kastrcn** [comment]
up

**Comment by judedaryl** [comment]
i fixed this issue by building a windows pc. i don't think they are going to prioritize this any time soon

**Comment by kr4uzi** [comment]
still an issue :( plus lots of microlags on mac (when a spell is used, i get a 0.5sec lag everytime).
