### ISSUE TITLE
Game crash on start after Summer2023 update (ArchLinux)

### ISSUE THREAD

**Issue by Bodyash** [ValveSoftware/Dota-2#2433]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/Bodyash/edce3ebfad45eff9b61364a48db08ea3): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Played a match before summer2023 update
Client updated
Start game - crash
Verify game files - everything is ok
Clean Vulkan Shaders cache, recompile, - still crashing, nothing changed

Radeon RX6600M, Ryzen 6900HX, 64GB ram
Linux 6.4.12 (played with this kernel for the whole day before client update)
Mesa and vulkan-radeon 1:23.1.6-4 (updated today)

First - I can see Dota logo
Then black screen and mangohud shows frametime graph (game already freeze):
![image](https://github.com/ValveSoftware/Dota-2/assets/2454569/31fd7bc3-bda5-4f16-bfce-2dd1707f31ea)
And finally crash

I have some dump files in /tmp/dumps, but can't upload them here (probably segfault)

![image](https://github.com/ValveSoftware/Dota-2/assets/2454569/e7c757df-8355-4d5e-a99f-d2b983cd8710)

running game with ./dota2.sh - show that something was uploaded somewhere (upload yes: ''CrashID=bp-4186114c-e31d-449d-90a6-658612230830'')

**Comment by limblendokin** [comment]
Wow, such a quick report. ANyways, experiencing same crash on endeavour os (mainline kernel 6.5)

**Comment by ConnahGriffin** [comment]
I face something similar to this. I use manjaro, updated the whole system and restarted it prior to opening the game after the new update. Not exactly similar with the difference being:

1.  Crash whenever I'm invited into a party.
2. Crash whenever a game is found. (I enabled desktop notification, not gonna test again with it off since it could tank my behavior score)
3. Crash when switching workspace and going back into it.

**Comment by tomasfarias** [comment]
Same issue as OP. I was running an older kernel which was still crashing. Attempted updating to latest kernel (which matches OP's version) but still crashing.

**Comment by sharkguto** [comment]
same here, i am using opensuse tumbleweed...

After dota2 upgrade today, stop working..


```bash
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x562048ba1040
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x562048b9e3b0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libschemasystem.so, got 0x562048c08ca0
Fossilize INFO: Overriding serialization path: "/home/sharkguto/.local/share/Steam/steamapps/shadercache/570/fozpipelinesv6/steamapprun_pipeline_cache".
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libmaterialsystem2.so, got 0x562062f4c3f0
Loaded libpangoft2-1.0.so, got (nil)
 failed to dlopen "libpangoft2-1.0.so" error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpanorama_text_pango.so, got 0x562062f6dde0
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 38: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 39: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 40: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 41: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 42: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 43: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 44: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 45: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 46: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 47: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 48: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 49: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 50: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 51: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 52: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 53: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 54: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 55: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 56: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 57: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 58: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 59: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 60: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 61: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 62: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 63: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 64: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 65: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 66: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 67: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 68: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 69: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 70: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 71: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 72: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 73: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 74: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 75: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 76: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 77: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 78: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 79: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 80: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 81: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 82: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 83: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 84: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 85: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 86: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 87: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 88: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 89: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 90: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 91: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 92: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 93: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 94: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 95: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 96: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 97: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 98: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 99: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 100: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 101: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 102: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 103: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 104: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 105: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 106: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 107: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 108: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 109: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 110: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 111: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 112: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 113: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 114: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 115: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 116: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 117: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 118: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 119: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 120: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 121: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 122: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 123: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 124: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 125: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 126: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 127: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 128: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 129: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 130: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 131: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 132: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/fonts.conf", line 133: unknown element "fontpattern"
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Loaded libfreetype.so.6, got 0x562062f6ede0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpanorama_text_pango.so, got 0x562062f6dde0
Loaded libfontconfig.so.1, got 0x562062f6f3c0
08/30 19:35:21 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(15809)
08/30 19:35:21 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(15809)
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libmeshsystem.so, got 0x5620630fedb0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libworldrenderer.so, got 0x562063111320
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvscript.so, got 0x562063123cb0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libnetworksystem.so, got 0x562063135f20
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libanimationsystem.so, got 0x56206314a280
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvphysics2.so, got 0x5620631606e0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libsoundsystem.so, got 0x5620631735b0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libscenesystem.so, got 0x562063189900
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libparticles.so, got 0x56206319eeb0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpulse_system.so, got 0x5620631b2b60
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libv8system.so, got 0x5620631c8470
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libserver.so, got 0x56206367f0a0
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libclient.so, got 0x5620636d7180
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpanorama.so, got 0x56206376b920
Loaded libmpg123.so.0, got 0x56206377f320
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libcairo.so, got 0x5620638d4000
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so, got 0x562048894010
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/dota/bin/linuxsteamrt64/libhost.so, got 0x5620638d4680
Loaded /home/sharkguto/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libscenefilecache.so, got 0x5620638e7dd0
^C08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(16575)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(16575)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(16638)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(16638)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(16665)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(16665)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(16678)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(16678)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230824204901)/tid(16696)
08/30 19:35:38 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(16696)
```

**Comment by koreanfan** [comment]
game crash after press accept match, debian 12 stable branch

**Comment by Bodyash** [comment]
UPD: https://steamdb.info/patchnotes/12073301/ - 6 minutes ago, still crashing.

**Comment by daveth91** [comment]
workaround: `-sw` launch option to start in windowed mode. bit annoying with a task bar but was able to play 2 matches with this

**Comment by mysticlizard** [comment]
Same issue, game crashes after logo fullscreen. Running arch linux updated today with latest mesa driver and AMD RX6600 like OP.

[crash.txt](https://github.com/ValveSoftware/Dota-2/files/12481208/crash.txt)

**Comment by tkachen** [comment]
Had same issue, but after latest update (https://steamdb.info/patchnotes/12073917/) it works again

**Comment by tomasfarias** [comment]
After the latest patch the issue is resolved for me.

**Comment by danginsburg** [comment]
I'm going to close this out - I pushed a fix last night for the crash and several have reported it fixed.  I looked up the initial crash reported here and it was because of running outside of the pressure-vessel steam-runtime and probably was not the same crash the user was experiencing when running from Steam (i.e. it stemmed from running dota.sh directly from the command-line and then missing .so's that are in the new Sniper Steam runtime).  That being said, if you are still experiencing  crashes, please feel free to open a new bug - crash ID's as were posted here are very helpful since I can then lookup the callstack.  Thanks.

**Comment by zub0r** [comment]
Client still crashes right after start.
error log: https://pastebin.com/raw/aYKKdcvE

**Comment by danginsburg** [comment]
Your crash is something else, it's running out of GPU memory and crashing.  I'm working on a fix for this, but it's a different bug than this.
