### ISSUE TITLE
[Linux] The game suddenly stopped launching

### ISSUE THREAD

**Issue by snorlax212** [ValveSoftware/Dota-2#2626]
#### Your system information

* System information from steam [(`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
[https://gist.github.com/snorlax212/2180315f60185037c4b1d518c651c361](https://gist.github.com/snorlax212/2180315f60185037c4b1d518c651c361)
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:

Today Dota 2 stopped launching on my Xubuntu 22.04.3. It pops no error, just goes from launching>syncing>runnings states to default (not opened). Steam 'Console' tab (with steam -console option enabled) doesn't provide useful info for me ([gist](https://gist.github.com/snorlax212/7a6bcf91c91d29e5d5ab722cbdb5d1c3))
![output](https://github.com/ValveSoftware/Dota-2/assets/8352523/f78c46dd-c656-4bb2-993b-fb67a2fb3d4a)
Terminal output with steam launched in it: [https://gist.github.com/snorlax212/71079abc0415dd87ce792761e9dd18ca](https://gist.github.com/snorlax212/71079abc0415dd87ce792761e9dd18ca)
Other games works OK. Re-installing is my last resort, but maybe I can provide some additional info to avoid this.
What else I've tried:

- Shader pre-caching On/Off (with re-downloading)
- Disabling In-Game overlay
- Disabling steam cloud
- Clear download cache
- Deauthorize All Devices
- Repair library
- Tried -safe and -autoconfig options 
- Deleted 'In-Game Overlay Data'
- Reinstalled package 'mesa-vulkan-drivers'

Dump from /tmp/dumps/ folder.
[crash_20231211180330_2.dmp.rename.txt](https://github.com/ValveSoftware/Dota-2/files/13637336/crash_20231211180330_2.dmp.rename.txt)

ADDED: Dota launches with **-vulkan_disable_pipeline_cache** launch option.

**Comment by nemoo2** [comment]
Same, the dmp file shows an error message
```
Assert( fatal stalled cross-thread pipe. ):/data/src/common/pipes.cpp:883
```

**Comment by nemoo2** [comment]
Issue is fixed, possibly due to patch or restart. Cannot reproduce anymore.

**Comment by snorlax212** [comment]
> Issue is fixed, possibly due to patch or restart. Cannot reproduce anymore.

Hi. My issue is still persist. Where can I check dmp file you mentioned above?

**Comment by nemoo2** [comment]
The dump file is under /tmp/dumps/<filename>.dmp . Its a binary file but it has ascii blobs you can read. Its not much use reading it though, you're better off restarting your machine or doing a fresh install?

**Comment by snorlax212** [comment]
Thanks. My /tmp/dumps/ folder is empty after launching dota via steam. I know fresh install is probably my last resort, but I'll try to wait some adept's answers to provide more info, I'm in no hurry :)

edit:
Dota  suddenly started to create *dmp files in /tmp/dumps/. I attached one in first post.

edit2:
Found out I can launch dota successfully with **-vulkan_disable_pipeline_cache** launch option. Never had any problems with vulkan before though.

Dota starts only with -vulkan_disable_pipeline_cache launch option

---

Issue transferred from https://github.com/ValveSoftware/Dota-2-Vulkan/issues/437.
@snorlax212 posted on 2023-12-12T16:28:28:

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/):
[System Information](https://gist.github.com/snorlax212/9e11f46536657ec147edde24937ef8c7)
[Steam Runtime Diagnostics](https://gist.github.com/snorlax212/677aca8ab881caf3ea425b3799c9aa1f)

* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes? (I'm on Xubuntu 22.04.3 LTS and didn't change anything)
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Two days ago Dota stopped launching. I create issue on Dota-2 tracker but later found out that -vulkan_disable_pipeline_cache launch option fixed issue for me, so I think it's vulkan related. First submit: [https://github.com/ValveSoftware/Dota-2/issues/2626](https://github.com/ValveSoftware/Dota-2/issues/2626)
Latest .dmp from /tmp/dumps/: 
[crash_20231212191400_2.dmp.rename.txt](https://github.com/ValveSoftware/Dota-2-Vulkan/files/13650681/crash_20231212191400_2.dmp.rename.txt)

**Comment by Strykar** [comment]
Same issue, `-vulkan_disable_pipeline_cache ` worked for a bit, and now its back to the same crashing on startup.
Arch linux, nvidia on Wayland.

**Comment by reevestrife** [comment]
Also experiencing the problem, But at the same time my counterstrike 2 also stopped working with the exact same behavior.  I see on the github issues for counterstrike there are lots of people with the same issue, so searching for solution there might also help. 
Counterstrike and Dota uses same game engine so it makes sense that both would stop working.

**Comment by jjoshi-space** [comment]
> **-vulkan_disable_pipeline_cache**

Likewise, disabling vulkan via launch option is not helping
Facing the same issue
[Ubuntu 23.10] UNABLE TO LAUNCH DOTA SINCE DAYS!

**Comment by reevestrife** [comment]
I tried the following now for this issue:

- Installed a fresh copy of Ubuntu 23.10 and immediately steam and dota  and nothing else - no joy, same issue continues
- tried a different version of the mesa kisak driver (AMD does not have gpu driver for ubuntu 23.10) - no joy, same issue continues.
- Installed a fresh copy of Ubuntu 22.04.3 LTS  immediately installed steam and dota - no joy, same issue continues.
- checked for dump folder after starting - no dump folder exists
- tried to start with `-vulkan_disable_pipeline_cache` - no joy, same issue continues.
- tried starting dota 2 through terminal with this command: `<steam path>/ubuntu12_32/steam-runtime/run.sh <dota path>/dota.sh` - this actually worked!!!! it started right up, but it seems its the running without context to steam, so you can't play online ...  But atleast it worked!! :-D
- tried starting dota 2 through through terminal with this command:  `steam steam://rungameid/373300` - this results in the same original problem of not launching. tries to launch - but then fails to launch with no error.  there is some output on the console of it starting up, and the pre launch dota 2 launch window pops up before it just stops abruptly without any error.

**Comment by Orbitoid** [comment]
I was having this issue and have had it a few times in the past. In my case I had installed some updates on my linux mint install through the update manager and I hadn't restarted yet. Once I restarted, everything started working again as before. This has happened to me in the past as well. Feels like a very Windows 98 SE solution to me but at least try it out if you haven't already.

**Comment by Potter32111** [comment]
I've updated my NixOS and now I'm facing with the same problem. When I boot to previous generation of OS dota 2 works well. I don't know what could've changed after update

**Comment by reevestrife** [comment]
@Potter32111  Make sure to install steam with a downloaded APK package so that it does not install with some other package manager like snap or flatpack, and this should solve your issue. It solved mine.  This is because of a bug on the new version that is fixed but not properly maintained or something like that.... either way it works if you directly install latest version of steam from a downloaded APK file.

**Comment by buncis** [comment]
this happens to me today
