### ISSUE TITLE
[Mac] Weird UI issue at lobby list

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#276]
<img width="1440" alt="screenshot 2015-07-26 01 41 44" src="https://cloud.githubusercontent.com/assets/5674597/8893115/9e08125a-3337-11e5-9975-4261983e2b4a.png">

The "Browse DotA Lobbies" text is cropped.

**Comment by gdrewb-valve** [comment]
Probably not a Mac/Linux issue.  What resolution are you running at?

**Comment by ssnl** [comment]
1440*900

**Comment by gdrewb-valve** [comment]
I can't repro this on Windows, Mac or Linux.  It's possible it has been fixed and that just hasn't made it out yet, we'll have to see after the next update.

**Comment by gdrewb-valve** [comment]
Did the 7/28 update change this?

**Comment by ssnl** [comment]
No. Still the same thing. I disabled wifi after starting the game, and successfully repro'd this

**Comment by gdrewb-valve** [comment]
We'll have to see if we can come up with a repro.

**Comment by gdrewb-valve** [comment]
Is this still happening?

**Comment by ssnl** [comment]
I'm not sure since I deleted Dota from my Mac and started playing on Windows

**Comment by gdrewb-valve** [comment]
OK, closing until we hear that it's still around.
