### ISSUE TITLE
Game menu and play very dark

### ISSUE THREAD

**Issue by oxycoder** [ValveSoftware/Dota-2#297]
I just get this problem on OSX 10.10.4
Any idea how to fix?
![screen shot 2015-08-04 at 6 11 17 pm](https://cloud.githubusercontent.com/assets/5463953/9059505/d5e63784-3ad4-11e5-9d15-7204d030bfc8.png)
![screen shot 2015-08-04 at 6 11 34 pm](https://cloud.githubusercontent.com/assets/5463953/9059506/d5f2ccd8-3ad4-11e5-9a0f-a9111cec7128.png)

Also the FPS on reborn are very low. I'm usually get 120 FPS at dota 2

**Comment by gdrewb-valve** [comment]
Can you post your system information from Steam?

**Comment by oxycoder** [comment]
This is my system information show from Help -> System Information in Steam

Processor Information:
    Model:  iMac14,2
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3997 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.4 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GTX 970

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x13c2
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.63" x 11.57"  (23.62" diag)
                                        52.4cm x 29.4cm  (60.0cm diag)
Primary VRAM: 2047 MB
```

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  1429319 Mb
    Largest Free Hard Disk Block:  200106 Mb

Installed software:
    Accessibility Inspector
    Adobe Photoshop CC 2014
    Agent
    Ampps
    Amupdate
    Android Studio
    App Store
    Application Loader
    Automator
    Battle.net
    Blizzard Error
    Calendar
    Chrome Remote Desktop
    Clover Configurator
    CodeKit
    Contacts
    Diablo III
    Diablo III Launcher
    FaceTime
    FileMerge
    Firefox
    G303Upgrade_v24
    G402Upgrade_v17
    G502Update_v16
    G910Upgrade_v12
    Game Center
    Gmail
    Google Chrome
    Google Drive
    Google Search
    GoTiengViet
    HipChat
    HWMonitor
    iBooks
    iExplorer
    Image Capture
    Instruments
    KingsRoad
    Launchpad
    Logitech Gaming Software
    Logitech Updater
    Logitech Webcam Software
    Maps
    Messages
    Microsoft Excel
    Microsoft OneNote
    Microsoft Outlook
    Microsoft PowerPoint
    Microsoft Remote Desktop
    Microsoft Word
    MiniTerm
    Mission Control
    MySQLWorkbench
    Notes
    Photos
    PhpStorm
    Realm Browser
    Reminders
    ShowHiddenFiles
    Solar App
    Soundflowerbed
    Steam
    Stickies
    TeamSpeak 3 Client
    TeamViewer
    The Unarchiver
    Uninstaller
    VMware Fusion
    Xcode
    YouTube

**Comment by danginsburg** [comment]
Can you post a screenshot of your video settings?  What do you have Brightness set to?

**Comment by oxycoder** [comment]
This is my video setting in games
![screen shot 2015-08-06 at 3 46 43 pm 1](https://cloud.githubusercontent.com/assets/5463953/9107570/65fe1840-3c52-11e5-8b22-56bbddde32ea.png)
The brightness in setting is set to 100%. I also try external monitor (Dell U2414H) via display port, but same problem

**Comment by danginsburg** [comment]
Can you try setting it to "Exclusive Fullscreen" and seeing if the Brightness slider helps at all?  It seems like some kind of gamma issue but I'm not sure how to repro it.  I haven't seen this here.

**Comment by oxycoder** [comment]
Still no luck with it. I have set brightness to 150%, the menu seem like better a bit, but game background still very dark.
![screen shot 2015-08-07 at 12 50 10 am](https://cloud.githubusercontent.com/assets/5463953/9119298/24ab5544-3ca0-11e5-894c-3f753fda6c8c.png)

I hope i'm not the only one get this problem 

p/s: I have tried install game on Fusion (windows 7), it look good, but very lag due to graphics card do not work on Fusion.

**Comment by gramathy** [comment]
I'm getting this as well after updating to 10.10.4. I got my UI (including the ingame HUD) to fix its gamma by going to windowed mode and back (normally I use desktop-friendly fullscreen) but in-game rendered views are still as oxy shows.
![screen shot 2015-08-16 at 7 23 58 am](https://cloud.githubusercontent.com/assets/750839/9293676/ae62f20c-43e8-11e5-98c8-ca1e9c09f824.png)
![screen shot 2015-08-16 at 7 29 30 am](https://cloud.githubusercontent.com/assets/750839/9293677/ae9a97de-43e8-11e5-81d2-c6f09039aca8.png)

<a href="https://gist.github.com/gramathy/5996562#file-gistfile1-txt">System specs</a>

**Comment by oxycoder** [comment]
@gramathy : I just open reborn today, it was fixed after upgrade system to 10.10.5. Try upgrade your OS to 10.10.5

**Comment by gramathy** [comment]
That's not a reason to close the issue, it's still not fixed.

**Comment by gdrewb-valve** [comment]
It depends, as if this is an OSX issue and not something in Reborn it won't be tracked here.  Can you check on whether updating helps?

**Comment by gramathy** [comment]
Nvidia only released their 10.10.5 web drivers today so I can now, but I'll have to wait until I get home.

**Comment by gramathy** [comment]
10.10.5 was a bit of a hassle to get working but it's currently working properly. 

With the reborn update between then and now I can't be sure which did it but it's currently fine right now.

**Comment by gdrewb-valve** [comment]
Thanks for the update and we're glad it's working.
