### ISSUE TITLE
Mac, hero is out of control, screen moving occasionally scrolls by itself

### ISSUE THREAD

**Issue by Spoonychopin** [ValveSoftware/Dota-2#2981]
<img width="276" alt="Image" src="https://github.com/user-attachments/assets/9e0a1f91-7262-4ef9-8315-208fb065a471" />

Issue Description
While playing Dota 2 on macOS, the hero is out of control, screen moving or not moving by itself:

After clicking, it takes about 2–3 seconds for the game to respond.
The camera occasionally scrolls by itself, as if receiving phantom input.
This makes the game nearly unplayable, despite the system itself not showing any significant CPU or memory bottlenecks.
Even in the demo hero mode.

Checked CPU & Memory Usage:
Dota 2 uses ~10% CPU.
System memory pressure is green, though swap usage is ~31 GB.
Closed Other Apps: Quit background apps (e.g., streaming software, chat apps), but the issue persists.
Steam Overlay Disabled: No improvement.
Verified Game Files / Reinstalled: No change.
Checked macOS Settings: Turned off Hot Corners and Accessibility features that could interfere with input.
Expected Behavior
Immediate or near-immediate response to mouse clicks and stable camera control, as is typical for Dota 2 on other platforms.

Additional Notes

Even though Activity Monitor shows high swap usage, the memory pressure remains green, and CPU idle is ~80–90%.
Network latency (ping) appears normal.
Any insight into potential fixes or further troubleshooting steps would be greatly appreciated. Thank you!

**Comment by Spoonychopin** [comment]
Now it is like, at the game start everything is ok, and 10-20min, I have to click twice to make the camera not move by it self, and always have to multiple click to select the hero. it's out of control basically.

I have to say, this situation ever happens after previous update, and I ever posted. like last OCT.
And after some update maybe you fixed it, it is back to normal for couple of month.
Hope you can fix it again, thx!

@kisak-valve @davidw-valve

**Comment by ishanjalan** [comment]
Happening to me too, and another friend of mine who is on mac as well

**Comment by yuvaraj91** [comment]
Mac M1 user here - same issue, started after patch 7.38

**Comment by xl-china** [comment]
same to Mac mini M2, please fix this problem quickly, I can't play it.

**Comment by AndreaVEH** [comment]
Panning the camera clockwise quickly can trigger the problem. Sometimes edge pan does not work, sometimes camera will stick down to the bottom or bottom right corner.

**Comment by ishanjalan** [comment]
Are you guys using software like Dropover/Clop/Yoink/ app that are triggered by gestures like hot corners? I had this problem a lot after 7.38 but after disabling those apps I mentioned while playing - greatly reduced the problem. It still persists but it's reduced.

**Comment by Spoonychopin** [comment]
> Panning the camera clockwise quickly can trigger the problem. Sometimes edge pan does not work, sometimes camera will stick down to the bottom or bottom right cornor.

Hey, you are correct! I checked in the demo hero mode,  "Panning the camera clockwise quickly can trigger the problem." this is exactly the reason!

@gdrewb-valve @kisak-valve @EricS-Valve @davidw-valve @mikela-valve

**Comment by AndreaVEH** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/24552#issuecomment-2707306181
Someone just found a temporarily solution to bypass the camera panning problem. **Turn off the Hot Corners.**

**Comment by SubvertDev** [comment]
@AndreaVEH did you even read the issue? It's not only about the camera and hot corners are already off

**Comment by kindacute** [comment]
Can confirm, really annoying when in the middle of the fight you screen flows away

**Comment by SubvertDev** [comment]
It seems that yesterday's update fixed this bug

**Comment by Spoonychopin** [comment]
> It seems that yesterday's update fixed this bug

great! I will check tomorrow. Previously 3 consecutive games were winningable but my faceless void cant ulty after 10-20min, very frustrated.

**Comment by kindacute** [comment]
not fixed for me, still screen scrolling by itself

**Comment by ishanjalan** [comment]
> not fixed for me, still screen scrolling by itself

Do you have apps that get activated based on mouse movement? For example, I have Dropover and Clop that activate when I move the mouse close to the edge of the screen (Notch for Dropover and bottom right for Clop)

**Comment by kindacute** [comment]
Yes, I have one, but I disable it when playing

**Comment by Spoonychopin** [comment]
> It seems that yesterday's update fixed this bug

tested, no, start an bot game, and got this problem from the very beginning, even worse @SubvertDev

**Comment by Spoonychopin** [comment]
There is a new Max update on the system, but I am pretty sure this issue still there.
I have no idea where or how we can let Valve know about it.
There are also a lot of reports on this Mac issue in the Steam DOTA2 discussion, but nobody has responded to it since Feb.20

@valve

**Comment by Spoonychopin** [comment]
Mar.15, changed new logitech mouse Pro 2DEX, issue still there. I ruined another game with my friend.

I will keep posting everyday now until valve fix it. SAD

**Comment by Spoonychopin** [comment]
Mar.16, reinstalled the Dota2; issue still there.

**Comment by SubvertDev** [comment]
Today's update broke the game again for me 👍

**Comment by Spoonychopin** [comment]
Mar.17 played two games today.
I thought the issue is fixed but after 15min it happened again, the second game is also crashed.
It's getting better, but the issue is still there.

**Comment by Spoonychopin** [comment]
Mar.18, there is an update but not fixed it yet.

**Comment by Spoonychopin** [comment]
Mar.21 played one game, I almost thought this bug fixed, much better, until 20min.

And I found something triggering. When put the mouse on the TOP-LEFT corner, and the camera cant stop till double click; when put mouse at other corners are fine. I tested multiple time, it maybe the reason.

**Comment by Spoonychopin** [comment]
Mar.22 played 2 games so far.
The first game was perfect, there is not issue, we were winning so I tested different click combination thought Valve fixed it.
The second game, this issue happened again, a few times that the camera locked need to press 1 multiple times; And put the mouse on LEFT-TOP corner the camera fly byitself.

In all, much better but not fixed yet.

**Comment by Spoonychopin** [comment]
Mar22-23, played 3 games later, this issue is absolutely not fixed.
The camera is either locked or out of control during the games.

**Comment by sunkaiiii** [comment]
Yesterday, I had the same issue during my second game. The first game was fine, but the problem started to worsen in the second game. My input began to lag, and the camera was out of control. There's definitely something wrong since the 7.38 update, as I've been playing on macOS for a long time and had no issues before this patch.

**Comment by Spoonychopin** [comment]
Mar.27, Played one game that no issue at all, Maybe it fixed already?

**Comment by Spoonychopin** [comment]
Mar.27
Played two games in the afternoon, it seems the bug fixed.
Played one game just now, the issue is still there, if mouse touched the left top corner the camera will scrolls by it self.

**Comment by Spoonychopin** [comment]
Mar.28 Played one game, issue happend at 10min
I wonder if Valve is going to fix it or not? Do something plz.

@kisak-valve @EricS-Valve @davidw-valve @gdrewb-valve @mikela-valve

**Comment by Spoonychopin** [comment]
@danginsburg Hi! You helped me on the Nestthone last year. Can you help or report this issue to the valve this time? I saw many discussions on steam as well. It's been two month, really need to play it normally. Thanks!

**Comment by Enigma-dev19** [comment]
Its been months since this issue was up and also the cursor clicks on another zip code

**Comment by Spoonychopin** [comment]
Mar.30th, played one game in the morning, the issue still there.
one game in the evening, it's clear no lag. Test tomorrow.

**Comment by Spoonychopin** [comment]
Apr.10 played multiple games this weem, not fixed yet.

**Comment by SubvertDev** [comment]
The game is unplayable for almost two months, is this ever gonna be fixed?

**Comment by peemaimarilyn** [comment]
Same issue here on macOS 15.3.2 (M2). Happens even when playing normally, not only spectating."

**Comment by barkntuncer** [comment]
same issue here, unplayable

**Comment by SubvertDev** [comment]
Is this on someone's radar in Valve? The game is unplayable from at least **February**
I see duplicates closed by @kisak-valve but does anyone work on a fix?
I can provide system details and/or video of this bug if that's of any help

**Comment by danginsburg** [comment]
The update we shipped just now should fix this.  Please retest.

**Comment by ishanjalan** [comment]
> The update we shipped just now should fix this. Please retest.

It's still happening.  Match ID: 8305127464 Around 17 minutes? I am the Dawnbreaker

**Comment by kindacute** [comment]
I quit playing Dota because of this issue :D

**Comment by barkntuncer** [comment]
I also verify this still happens and it's making me quit as well

**Comment by SubvertDev** [comment]
I had a fresh install after new update, played for a week, seems to be fixed

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by ishanjalan** [comment]
It is definitely not fixed. I reinstalled it based on their comment but the issue persists.

> Closing per the last comment.

**Comment by oscar-gallog** [comment]
This is still happening today on Mac OS Tahoe

**Comment by Spoonychopin** [comment]
well it happens again after the newsest update of mac system.

unlike other cases, I can play, but still the mouse problem and also the screen is keep shinning.

@danginsburg

**Comment by AndreaVEH** [comment]
I think there's a conflict with the new feature Game Overlay introduced in macOS Tahoe. For example:

1. Switching from Dota 2 to another app and back to Dota 2 will make camera panning of the top edge dysfunction while panning from other three edge works normally.
2. Pressing Command + Esc to show Game Overlay menu will make camera panning of the right edge dysfunction while panning from other three edge works normally. But after hiding the Game Overlay menu, camera panning will work without any problem.

When you are in the first situation, there is an ad hoc fix. Pressing Command + Esc to show Game Overlay menu and move mouse to the top edge to make sure camera panning of the top edge working. Then pressing Command + Esc to hide Game Overlay menu and everything will go as usual.

@kisak-valve @danginsburg

**Comment by ishanjalan** [comment]
> Replying to https://github.com/ValveSoftware/Dota-2/issues/2981#issuecomment-3318896004

Yep this is what I am facing as well. My initial post was my first experience with it but I figured out how to make it work consistently by messing around with video settings.

**Comment by Spoonychopin** [comment]
Hello Valve,

Happy New Year!

Recently, the game has been mostly fine, but occasionally it becomes a bit out of control for about 5 seconds.

The main issue is that in every first game I start, the timer reaches 00:00 and the battle begins, the game becomes extremely laggy. The only way to fix it is to completely quit Steam and restart it. After restarting, the game usually returns to normal within about 1–2 minutes. Happens everyday, and the second and third game runs well.

This issue has happened before, but not within the past two years.

Hope you can take a look, and fix it if possible, thanks!

@kisak-valve @davidw-valve @davidw-valve @danginsburg

**Comment by ishanjalan** [comment]
unfortunately, this is my experience as well. Mostly fine, but goes out of control once in a a while. I don't know why this has been such a longstanding issue now...

> Replying to https://github.com/ValveSoftware/Dota-2/issues/2981#issuecomment-3703343980

**Comment by Spoonychopin** [comment]
this hug lag start around 00:00 and end at around 02:30; means I have to sacrifice the first 2min30sec of this game
