### ISSUE TITLE
[Linux] Modifier keys such as Alt perform actions which minimize the game.

### ISSUE THREAD

**Issue by ramma** [ValveSoftware/Dota-2#30]
This issue was reported originally [here](https://github.com/ValveSoftware/Dota-2/issues/1740) and still exists in the Reborn beta.

> Modifier keys, such as the Windows/Super key or more importantly the Alt key, are no longer prevented from performing actions on the desktop that cause the game to minimize. Those keys in particular open parts of the Ubuntu dashboard, which causes the game to minimize.
> 
> Prior to the April 23rd patch and the test client build modifier keys could be bound and used in game with no issue (such as windows/super for stop). After these updates, the game is minimized any time a key is capable of interacting with the Ubuntu dashboard.
> 
> System info https://gist.github.com/ramma/925cc19fb6fd7805979e

**Comment by mfonville** [comment]
I actually had not this issue in the old client, but in the new client it does happen (but not all the time, it is very inconsistent)

**Comment by CommanderAlchemy** [comment]
Same here, Dota 2 was able to catch the alt key but now it seems that the Window manager gets it instead so I cannot broadcast alerts etc ingame.

**Comment by davidw-valve** [comment]
Are you running the game fullscreen or windowed? Which window manager are you using?

I am not reproducing this at all.

**Comment by mfonville** [comment]
I am running with a borderless window in Unity.

Part of the problem may be, that I tend to have other windows in focus, before loading a match. Though in the old Dota2 this was not a problem.

Current trick, that since the latest versions work, is that when the match starts, I return to the menu, within the menu I alt-click and ctrl-alt-click the window, I change focus to the title bar of the window, when i then go back into the game, the issue has disappeared. (the action scheme might be a bit Pavlov-generated, but it works in 100% of the cases).

**Comment by ramma** [comment]
Running with "Use my monitors current resolution", and using default everything from Ubuntu 14.04(Compiz window manager).

As mentioned in the [Source 1 report](https://github.com/ValveSoftware/Dota-2/issues/1740) of this issue, the problem started after overlay updates in late April. That may just be coincidental though as disabling the overlay doesn't fix it for me.

**Comment by mfonville** [comment]
An updated: currently I only need to go back from game to the menu, and then back to the game again, to solve the problem.

**Comment by Turmfalke2** [comment]
Isn't the window manager always supposed to have priority? If this gets changed I would lose control over my wm while playing dota, which would be pretty bad.

**Comment by ramma** [comment]
This issue is still present after the September 8th updates. To add to the problem, the Super/Windows key cannot be bound to anything in settings either. Without rebinding Windows/Super key and Alt, the game is unplayable due to the constant minimizing. Switching between windowed or full screen does not solve the problem either.

**Comment by guillevc** [comment]
i'm also experiencing this

ubuntu 14.04

**Comment by gdrewb-valve** [comment]
Note that in the Advanced section of hotkey settings you can select to allow the Windows / Command key to be bindable.

**Comment by u00101010** [comment]
This issue does still exist in Ubuntu 15.10 with the latest DOTA 2 updates.

And actually, to me it does not happen every single time. There are special occasions when I'm actually able to Alt-click stuff on the screen without the game getting minimized. I will continue to further observe this and report back as soon as I have something.

**UPDATE**: It seems like it does not happen if I manage to press Alt and click in exactly the same moment. If I press Alt and then not click immediately, Unity decides to show up.

**Comment by vadi2** [comment]
It's still an issue. Enabling Windows/Command key to be bindable doesn't help, and I can't bind to something else even after enabling it. Pressing the left Alt key opens up the HUD for me (https://wiki.ubuntu.com/Unity/HUD) and minimizes the game, so it's pretty disruptive.

**Comment by u00101010** [comment]
It still does not happen to me always, but now I just can't see the pattern. After a few "successful Alt-clicks" that did not trigger the HUD, the upcoming alt-clicks will be unsuccessful no matter how simultaneously I press alt and click. Well, technically, the alt-click _is_ successful because the info will be written in chat, but then the window minimizes.

Perhaps making this "alt-click" key bindable would solve the issue for Ubuntu users. So instead of alt we would press something else and everyone will be happy.  :blush:

**Comment by vadi2** [comment]
It's not alt click - just press and release alt, and the HUD comes up. It's
a unity feature. The issue is that dota isn't consuming the event while in
full screen, in my opinion.

**Comment by gdrewb-valve** [comment]
Reborn just uses SDL for fullscreen and doesn't do any of its own handling.  I've asked the SDL devs if there's something they can do.

**Comment by vadi2** [comment]
Thanks Drew!

**Comment by gdrewb-valve** [comment]
After discussion with the SDL devs there doesn't appear much that SDL can do.  The window is decorated as a fullscreen window and after that it's up to the window manager as to whether it allows WM behaviors or not.  Closing this as it's not a Reborn issue.

**Comment by vadi2** [comment]
Have any players found a workaround on this? Given the prevalence of alt+clicking, if you stuff that up and just press alt, the game will minimize at the most inopportune times.

**Comment by Tele42** [comment]
@vadi2 adjust your DE's hotkeys to use a different modifier for those actions (I recommend Super/Meta).

**Comment by vadi2** [comment]
That's already taken by another action, both Super and Alt do different things.

**Comment by Tele42** [comment]
@vadi2, my point is that no application has the right to block your DE's hotkeys. If you choose to have troublesome key combinations and you have control over the hotkeys, that's your problem, not the games.

**Comment by vadi2** [comment]
I don't need your opinion on whose problem it is, I'm asking if anyone else has found a workable solution. This is the default on Ubuntu, so I imagine a fair bit of people are affected by this.

**Comment by u00101010** [comment]
> I don't need your opinion on whose problem it is, I'm asking if anyone else has found a workable solution. This is the default on Ubuntu, so I imagine a fair bit of people are affected by this.

The current working solution is to rebind the "Alt" key in the game settings to something else.

**Comment by ramma** [comment]
@vadi2 My solution is rebinding the keys in CCSM. I've bound super to alt+super and alt to shift+alt, neither of which combos being used in my game settings. It's far from ideal, but works till this is fixed, if it ever is.

@Tele42 My understanding is that's only the case in "fake" fullscreen, which Dota is using in reborn. In "real" fullscreen you'd expect those key presses to be captured by the program unless it is not focused. Specific event handling for combos like alt+tab need to be used to keep the window from taking complete control though. The current use of "fake" fullscreen also causes an issue where mouse clicks are sent to windows under them, which require one or two alt-tabs to fix.

**Comment by Locustv2** [comment]
Has anyone been able to solve this issue?
I am using Ubuntu 16.04 and this is very annoying.
Everytime i press alt and do not press any other key the command overlay appear.

I have 2 screen and sometimes in action i move my mouse to the other screen totally lose focus on the dota2 client... :/

**Comment by smarteist** [comment]
Year 2021 and still have this issue, temporary solution is using ALT+TAB to minimize and then maximize the game. using mouse to maximize the window will cause this problem.
