### ISSUE TITLE
[Mac] "attempt to get item stock time for unknown stock item..." affecting performance

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#364]
When demoing heroes, I get error messages filling the console (they flow at a high rate). This is associated with poor frame rate. Every game (played or spectated) gets affected by the issue after that. The only fix is to restart dota 2 and be sure not to demo a hero again. 
![capture d ecran 2015-09-05 a 14 17 36](https://cloud.githubusercontent.com/assets/4463576/9699190/b424fb08-53d9-11e5-813b-06f4bcfd4e4a.png)

System info 
ocessor Information:
    Model:  MacPro1,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2660 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.9.5 (64 bit)

Video Card:
    Driver:  AMD Radeon HD 7950

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
```

   Primary Display Size: 16.97" x 10.71"  (20.04" diag)
                                            43.1cm x 27.2cm  (50.9cm diag)
    Primary VRAM: 2047 MB

Memory:
    RAM:  8192 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  704196 Mb
    Largest Free Hard Disk Block:  74414 Mb

**Comment by jeanlain** [comment]
It's probably not Mac-specific. Others are reporting the issue.

**Comment by danginsburg** [comment]
I believe this has been fixed as I am not able to repro it, but can you provide exact repro steps so we can be sure?

**Comment by jeanlain** [comment]
I just start dota 2 reborn and immediately demo a hero. It doesn't appear to depend on the hero. Graphics setting are set to max except for ambiant occlusion. 
I still get the issue after the latest patch.

**Comment by justSQL** [comment]
I get this on Windows 7 x64 also - so it's not an Os X / Linux specific issue.

**Comment by jeanlain** [comment]
Alternatively I also see this console message in the demo hero map. The consequences are the same: lower fps. 
![capture d ecran 2015-09-09 a 21 34 24](https://cloud.githubusercontent.com/assets/4463576/9773417/5781ffd8-5742-11e5-8bb5-6490f0a15615.png)

**Comment by gdrewb-valve** [comment]
Both of these spew items should be fixed now, is this issue still active?

**Comment by gdrewb-valve** [comment]
Closing for now.
