### ISSUE TITLE
[OSX] Green Boxes obstructing HUD + Purple/Black Texture Failure

### ISSUE THREAD

**Issue by blakeb155** [ValveSoftware/Dota-2#372]
A little bit similar to #352, however that one is on Linux

All UI/Menu items run fine, in-game HUD is obstructed by green boxes and some items are missing textures (purple/black)

Additionally,  when my hero dies the screen goes dark (same issue as #309)

Specs:

MB Pro 15'' Retina Display Mid 2014
2.2Ghz Intel Core i7
16GB 1600 MHz DDR3
Intel Iris Pro 1536MB
OS X 10.9.5

<img width="1440" alt="screen shot 2015-09-06 at 7 39 34 pm" src="https://cloud.githubusercontent.com/assets/13469795/9715821/70412f9a-55a7-11e5-850e-bdff76c43894.png">

**Comment by danginsburg** [comment]
I have not seen this issue.  Are you able to update to OS X 10.10.5 to see if it fixes the problem?  Have others seen this with any other configs?

**Comment by danginsburg** [comment]
@blakeb155 What language do you have your computer set to?  We saw an issue in #352 that turned out to be related to Turkish language that we fixed.  I wonder if this is the same, but on OSX.

**Comment by blakeb155** [comment]
Hi Dan,

Have updated to 10.10.5 and can confirm the issue still persists.

OS language is set to English (Australian)

**Comment by blakeb155** [comment]
I've also noticed the buttons for Hero Selection and Random Hero are missing/incomplete as per below

<img width="1005" alt="screen shot 2015-09-13 at 4 21 47 pm" src="https://cloud.githubusercontent.com/assets/13469795/9835547/fc4c2e32-5a33-11e5-82d9-85b8bf8e48f6.png">

**Comment by blakeb155** [comment]
I just verified integrity of game cache and it identified that there were almost 700mb files missing.

After updating, the bug is now fixed.
