### ISSUE TITLE
[MAC] Graphics freeze randomly during play

### ISSUE THREAD

**Issue by SirBlondie** [ValveSoftware/Dota-2#447]
Similar to problem #345, but more random, and more recoverable.

I can start a bot match, play for a random period of time, then the game will freeze. Use Ctrl+Left or Right to switch desktops, and as it switches I hear the game update, switch back, and often the game screen has gone to black, switch back and forth two or three times, and the game will recover, and I can play to the end, although it may freeze another time or two.

System : Mac Pro 2010
Graphics Card : Sapphire Radeon HD 7950
OS : 10.11 GM (I know not released, but pre-Reborn, no issues, and it is GM)
Dev tools installed if you want me to trace something.

**Comment by SirBlondie** [comment]
Processor Information:
    Model:  MacPro5,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2c
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3330 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.0 (64 bit)

Video Card:
    Driver:  AMD Radeon HD 7950

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x679a
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  3200 x 1800
Desktop Resolution: 6400 x 3600
Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                        59.7cm x 33.6cm  (68.5cm diag)
Primary VRAM: 2047 MB
```

Memory:
    RAM:  24576 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  2122645 Mb
    Largest Free Hard Disk Block:  917976 Mb

**Comment by gxgani** [comment]
Is your in-game overlay working?

**Comment by SirBlondie** [comment]
No, I just tried it, it does not work. Checked settings, it is enabled and on the default keybinding.

**Comment by SirBlondie** [comment]
Just FYI, installed most recent update, no change.

**Comment by PimientoMoruga** [comment]
Same for me i can only play against bots and finish to freeze (i must do hard reboot), for the others the map is loading but when start i've just a map with every player disconnected and the game bring me back to the main menu.
It was working well with source and crash every time with reborn. I've verified game's files with steam (all looking allright), verified mac permissions, uninstall/reinstall severall times nothing work.

```
MacOS Version
Version 10.10.4

iMac
Processor 2,8GHz intel Core 2 Duo
Mémory 4 Go 667 Mhz DDR2 SDRAM
Graphism ATI Radeon HD 2600 Pro 256 Mo

24-pouces (1920 x 1200)
ATI Radeon HD 2600 Pro 256 Mo
```

Stockage :
    212,29 Go / 499,25 Go

**Comment by danginsburg** [comment]
@PimientoMoruga Your issue should be fixed with the 9/18 update today.

**Comment by PimientoMoruga** [comment]
Fixed, thx a lot.

**Comment by SirBlondie** [comment]
Unfortunately my issues remain. Is there any further information I can provide?

**Comment by danginsburg** [comment]
@SirBlondie If you could run with -con_logfile and provide game/dota/console.log that would be helpful.   I am going to get a HD 7950 for my MacPro 3,1 which I used to repro the ATI 2600 problem to see if I can repro your issue.

**Comment by SirBlondie** [comment]
No problems, will look to collect that for you, and I realise that I probably have a fairly rare system, so understand if it get's too hard to debug. 

I'm actually a little suspicious that it might be an OS X issue rather than on your end, but it's certainly was the case that swapping between DOTA2 and Reborn prior to the change over, I had stability issues with Reborn that kept me on the older version.

Matt

## 

Matthew Wallis
mattw@madmonks.org

**Comment by SirBlondie** [comment]
Console log attached.

Matt.

**Comment by danginsburg** [comment]
I am not seeing the console log, could you try to post it again?

**Comment by SirBlondie** [comment]
Odd, sent folder email definitely has it attached. Perhaps zipped files stripped on server?

Attaching uncompressed.

**Comment by Tele42** [comment]
@SirBlondie you're posting to an issue tracker via an email interface, not a mailing list. Please use a pastebin to attach logs (https://gist.github.com/ is the recommended default).

**Comment by SirBlondie** [comment]
Apologies, uploaded log file to gist.

https://gist.github.com/SirBlondie/267f7a9cbcd1e98456ee#file-console-log

Matt

**Comment by SirBlondie** [comment]
Suspect I have figured it out. Looks like notifications coming in while DOTA2 is running, are causing it to hang. I’ve now had hangs while sitting at main menu. Turned off notifications, and played through the first game in ages with only minor, half second pauses. 

Will explore some more but thought I should pass it on.

Matt.

**Comment by SirBlondie** [comment]
Actually, spoke too soon. Still having regular pauses, but they’re about 5 to 10 seconds, rather than 20 as they have been.

Matt.

**Comment by danginsburg** [comment]
@SirBlondie I have installed an AMD Radeon 7950 in a MacPro 3,1 to try to reproduce your issue.  I am not seeing 5-10 second pauses.  At most, I see small hitches on the order of 250-500ms caused by shader compiles.  Can you check if that is what you are noticing?  If you run with -gl_time_shader_compiles and keep the console open you will see a message whenever a shader compile occurs.  See if those correspond with your hitches.

Unfortunately, there is not a lot we can do about that problem if that's what it is.  We use GL_ARB_get_program_binary to speed shader loading performance on drivers that support it (OS X does not).  Also, many OpenGL drivers on Windows/Linux cache shader compiles themselves to reduce hitching.  Unfortunately, we have no control over whether drivers choose to do that on any platform.  Without program binaries or an internal driver cache there will be some hitching.  The alternative of precompiling all of our shaders is not practical without abhorrent load times.

**Comment by SirBlondie** [comment]
Yeah, nothing like that. If it was 250 - 500ms, I wouldn’t be complaining. This is definitely long enough that I can take both hands off the keyboard, crack my knuckles, put them behind my head and whistle.

Looking in console I see a lot of shader compiles taking 41ms, and then a lot of deferred shader compiles. And there’s 100’s of them, if this was happening as often that throughout the game I would have stopped playing. This happens no more than 3 or 4 times a game.

If you still have access to the Mac Pro can you set up an email account on it and get someone to email you a bunch of times during a game? I still suspect there’s an interrupt coming from outside the game from OS X Notifications or something similar, that’s triggering the pause.

If not, then thanks for you efforts anyway.

Matt.

**Comment by danginsburg** [comment]
@SirBlondie Are the stutters still occurring for you?  I was unfortunately never able to repro this bug.  I wonder if any of the many fixes we have made might have addressed this problem.

**Comment by SirBlondie** [comment]
Hi Dan,

No, no longer happening, I think I pretty much tied it to something to do with notifications coming in while I was playing. I’m pretty sure it was an Apple update that finally cleared it all up, though there seemed to be a couple of DoTA updates that improved it too.

Now I just need you to top making the bot’s so good at rolling me.

Thanks for your efforts.

Matt.

**Comment by danginsburg** [comment]
Great, glad to hear it!  Closing
