### ISSUE TITLE
[Linux] When playing in windowed mode mouse sometimes is not restricted to window.

### ISSUE THREAD

**Issue by MaikuMori** [ValveSoftware/Dota-2#450]
Sometimes when the game starts the mouse is not restricted to window borders which causes you to click outside window and lose focus (especially when panning the screen).

This seems to be caused by alt-tab'ing in lobby and/or game window, but I don't have exact steps to reproduce it.

It can be fixed in-game by going to options and changing resolution or window mode.

I'm also quite sure this is not just happening in windowed mode.

Desktop Environment: Gnome

**Comment by ramma** [comment]
This sounds like it may be related to the problems reported in issue #30, seeing as it involves input not being capture exclusively by Dota. My understanding from gdrewb-valve comment on issue #101 is that there is no true full screen in reborn (which may explain these issues).

**Comment by budimanjojo** [comment]
Latest update log shown this:
Fixed an alt-tab issue on multiple monitor systems that would fail to confine the mouse upon resuming the game.
Maybe you can try again? On me it locks the mouse immediately after alt tabbing into dota 2 "when" I was ingame.

**Comment by MaikuMori** [comment]
I can confirm that I still have this bug. I was alt tabbing while waiting for a game and then in lobby as well. When the game started the mouse was not confined. I tried to tab out and back in and it still didn't work. Had to fix it by changing resolution.

**Comment by budimanjojo** [comment]
Can you post the screenshot or a short video? I'm curious :)

**Comment by MaikuMori** [comment]
Grr, gif turned out too big for GitHub, here's the movie:
http://webmshare.com/play/n80zN

**Comment by budimanjojo** [comment]
Okay, did you try using borderless window?

**Comment by MaikuMori** [comment]
Yep I encounter this in all modes - windowed, fullscreen, borderless.

**Comment by hartigan43** [comment]
This occurs with Arch in Plasma (KDE 5) as well.  The most recent patches seemed to have make it occur less often.  Also toggling between Desktop-friendly fullscreen fixes the issue for me without having to choose a new resolution or change from fullscreen to windowed.  I can provide more information if necessary but as mentioned by MaikuMori, I also cannot reliably reproduce it.

**Comment by ageisen2000** [comment]
This is still an issue for me (Ubuntu Gnome). My workaround currently is to open the main menu again from in game (top left corner) and then go back into game.

**Comment by danginsburg** [comment]
Alt-tab'ing during load allows me to reproduce this reliably as described in #503.

**Comment by danginsburg** [comment]
This issue has been fixed and will be in a future Dota 2 update.

**Comment by danginsburg** [comment]
The fix has been released.  Closing.

**Comment by igormp** [comment]
After the latest battle pass update, it seems like this issue is back, during gameplay in a window the mouse sometimes goes out of the game screen, thus making it lose focus.

**Comment by riv0tril** [comment]
Same for me, sometimes like always

**Comment by gomes1876** [comment]
im with this problem :(
