### ISSUE TITLE
Chinese does not render correctly on Mac Reborn Client 

### ISSUE THREAD

**Issue by zkzipoo** [ValveSoftware/Dota-2#457]
Model：MacBook Pro (Retina, 13-inch, Mid 2014)
OS：OS X 10.10.5

I've currently set the default OS language to be EN, steam to be Chinese and Dota 2 Reborn to be Chinese. 

When in a game, most of the Chinese characters are fine but those above the hero (the one shows the players' name) are invisible. Only en ACSII characters are rendered properly (displays well) but the field for Chinese player names are empty. I'm not sure whether it is related to #392 (Korean Characters). If so, could anyone tell me which fonts to be used on my Mac? thx

PS: All the Chinese characters in Scoreboard are fine

**Comment by danginsburg** [comment]
Could you please a screenshot?  I don't speak Chinese so it would help to have the exact issue shown from a Chinese speaker.  Thanks.

**Comment by zkzipoo** [comment]
Thanks for replying, danginsburg
Firstly, numbers and ascii characters are rendered correctly as shown below
<img width="297" alt="screen shot 2015-09-17 at 11 33 06 pm" src="https://cloud.githubusercontent.com/assets/3366892/9937759/a58ab3c0-5d94-11e5-87b6-f7bc7f98c506.png">
Secondly, if the players name contains both Chinese and English, only English parts remain
For example, the player who plays doom is called "你TM来杀我啊", only "TM" left
<img width="428" alt="screen shot 2015-09-17 at 11 32 18 pm" src="https://cloud.githubusercontent.com/assets/3366892/9937830/fb4e5280-5d94-11e5-8380-e5dc0ce1c835.png">
<img width="888" alt="screen shot 2015-09-17 at 11 32 34 pm" src="https://cloud.githubusercontent.com/assets/3366892/9937839/069eb6ac-5d95-11e5-9f2c-b51acad773a2.png">
Last but not least, the biggest problem comes, the player with a full Chinese name won't render
<img width="483" alt="screen shot 2015-09-17 at 11 42 40 pm" src="https://cloud.githubusercontent.com/assets/3366892/9938016/d7c8382a-5d95-11e5-8ce5-7fb8a04fdb2b.png">
As you can see, the player who plays TA uses a name "地王盖天虎" but there's nothing shown above the blood bar as well as the hitbar, only his level left as 17

Thanks again

**Comment by timxx** [comment]
The same problem on linux platform. It seems that dota2 uses arial font internal which doesn't support Chinese.

**Comment by zkzipoo** [comment]
Have you figured out a workaround, @timxx ? I've tried to look into those configurations but failed to get a clue.

**Comment by zkzipoo** [comment]
![screen shot 2015-09-18 at 4 09 39 pm](https://cloud.githubusercontent.com/assets/3366892/9955081/b90a0fa4-5e20-11e5-970e-b8d5d2fae3c9.png)

seems found something here, it's about the font config of infinality which is available at https://github.com/Infinality/fontconfig-infinality/tree/master/infinality

according to the repo above, it saids I can customize my own render style, but there is a question, all the configs found in my Mac Steam folder are about os-win. I think os-win means Windows family and I cannot find anything about OSX. @danginsburg is that relative? or is there a workaround available? thanks again

**Comment by danginsburg** [comment]
I have this repro'd here and understood.  We are looking into a fix.

**Comment by zkzipoo** [comment]
thank you and looking forwards to a solution

**Comment by danginsburg** [comment]
Fixed.  The fix will be in the next Dota 2 release.

**Comment by danginsburg** [comment]
The fix is in the 9/22 update.

**Comment by zkzipoo** [comment]
Thx, I will comment here if it is solved. Really appreciated.

**Comment by danginsburg** [comment]
I'm going to close this out, it should be fixed for you.  If not, let me know and I can repoen it.

**Comment by zkzipoo** [comment]
Hey @danginsburg , it seems the problem still exists, just as I've posted before.
I will post some specs of my computer.

### computer and os

#### ![image](https://cloud.githubusercontent.com/assets/3366892/10064149/0c2b1ff8-62a8-11e5-9477-5b495f6d2586.png)

### language

#### ![image](https://cloud.githubusercontent.com/assets/3366892/10064162/28cbc39c-62a8-11e5-8c4b-f8204c5191d8.png)

### dota2 content id

###### 7827245 and I've verified the local content

### dota2 language

###### Chinese

### steam language

###### Chinese

**Comment by danginsburg** [comment]
Can you do me a favor, can you try running with -language schinese on the Launch Options and see if it works?

**Comment by zkzipoo** [comment]
It works this time by adding the launch settings.
But it is still bit weird when showing Chinese Characters. The font size seems unequal.
![image](https://cloud.githubusercontent.com/assets/3366892/10073516/16242cee-62fc-11e5-81c0-667addefa423.png)

But in all, this was a big help and really appreciated.

**Comment by danginsburg** [comment]
The problem is to do with the way the code is detecting language.  I will keep this open until I fix that issue.

**Comment by zkzipoo** [comment]
thanks

**Comment by timxx** [comment]
@danginsburg Is it also fixed linux platform? At least isn't work for me, I'm using ArchLinux 64bit, with en_US locale and launch dota 2 with **-language schinese** option. What font shall I installed?

**Comment by zkzipoo** [comment]
@timxx add Chinese as system secondary language ?

**Comment by danginsburg** [comment]
@timxx This is not also fixed on Linux, there is still an issue there.  It has only been fixed on OS X so far.

**Comment by danginsburg** [comment]
This is fixed on OS X, will track for Linux in #488.

**Comment by richardmatthias** [comment]
As of March 10, 2016, the newest Dota2 client still displays Chinese characters over heroes (and only there) in an unequal fashion.
