### ISSUE TITLE
Using timbersaw's chakram then selecting new hero in demo mode crashes dota

### ISSUE THREAD

**Issue by 420git** [ValveSoftware/Dota-2#984]
Tested on both linux and win xp

steps to reproduce:
1.select timbersaw in demo mode
2.send chakram and dont return it
3.select new hero
4.mana keeps getting spent
5.when mana is over dota crashes

**Comment by ramma** [comment]
If it happens on Windows, then the dev forums are a better place to report.

Either way, I confirmed this on Linux([sys info](https://gist.github.com/ramma/925cc19fb6fd7805979e)).

**Comment by gdrewb-valve** [comment]
ramma is correct that this forum is for bugs that only happen on Linux and Mac.  General issues should be posted at dev.dota2.com

I've passed this on.

**Comment by ramma** [comment]
@gdrewb-valve Slightly off topic, but who would I poke about not receiving a password reset email for the forums? Haven't been able to get in since the database issues email a few days back.

**Comment by gdrewb-valve** [comment]
I'll check.  I might not hear back until Monday, though.

**Comment by gdrewb-valve** [comment]
This has been resolved so you should be getting your reset email / able to request a new reset email.

**Comment by ramma** [comment]
I'm still not getting anything. Even added the email which the notice was sent from to never go to spam.

**Comment by gdrewb-valve** [comment]
I passed this on and supposedly it's really fixed and it's just taking it's time to work through the system.
